name: n9
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.5.0
  intl: ^0.19.0
  flutter_datetime_picker_plus: ^2.0.1
  flutter_localizations:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  audioplayers: ^5.1.0
  sleek_circular_slider: ^2.0.1
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0  
  cloud_firestore: ^4.9.1
  get_storage: ^2.1.1
  lottie: ^2.6.0
  curved_carousel: ^0.0.7
  image_picker: ^1.0.4 
  firebase_storage: ^11.4.0
  timeago: ^3.6.0
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  webview_flutter: ^4.4.2
  firebase_messaging: ^14.6.4
  glassmorphism: ^3.0.0
  scroll_datetime_picker: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/SignikaNegative-Bold.ttf
        - asset: assets/fonts/SignikaNegative-Light.ttf
        - asset: assets/fonts/SignikaNegative-Medium.ttf
        - asset: assets/fonts/SignikaNegative-Regular.ttf
        - asset: assets/fonts/SignikaNegative-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

