import 'package:get/get.dart';

class AppLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcome': 'Welcome to',
          'appName': "N9 DESTINY HUB",
          'appSlogan':
              "Your Path to Happiness, Love, and Abundance Starts Here: Get Your Personalized Horoscope, Meditation, and More!",
          'start': 'Get Started',
          'know': "Let's know each other",
          'nameQuestion': 'How can I call you?',
          'name': 'Name',
          'birthQuestion': 'When were you born?',
          'birthOfDate': 'Birth of date',
          'timeQuestion':
              'To make precise predictions, I also need to know your time of birth. If you do not know it, just select 12:00',
          'time': 'Time of birth',
          'cityQuestion': 'Write down your city of birth',
          'city': 'City',
          'wrongEmail': 'Email is wrong',
          'noInfo': 'This field can not be empty',
          'description': 'Description',
          'love': 'Love',
          'character': 'Character',
          'career': 'Career',
          'health': 'Health',
          'rulingPlanet': 'Ruling planet:',
          'tarotCard': 'Tarot card:',
          'element': 'Element:',
          'bestCompatibility': 'Best Compatibility:',
          'readMore': 'Read more',
          'aries': 'Aries',
          'taurus': 'Taurus',
          'gemini': 'Gemini',
          'cancer': 'Cancer',
          'leo': 'Leo',
          'virgo': 'Virgo',
          'libra': 'Libra',
          'scorpio': 'Scorpio',
          'sagittarius': 'Sagittarius',
          'capricorn': 'Capricorn',
          'aquarius': 'Aquarius',
          'pisces': 'Pisces',
          'english': 'English',
          'russian': 'Russian',
          'azerbaijani': 'Azerbaijani',
          'hello': 'Hello',
          "next": "Next",
          "statistics_heading":
              "90% of our users said they feel more connected to their daily horoscope",
          "statistics_title":
              "This app has completely transformed my mornings! I used to rush through the day without a second thought, but now I start each morning by checking my horoscope and reading what others are saying. It helps me feel more grounded and connected.",
          "statistics_subtitle":
              "Join thousands of others and start your journey with us today.",
          'birthdate_register':
              "To provide you with a personalized horoscope, we need to know your birth date, which is essential for determining your Sun sign",
          "check_love": "Discover Your Love Compatibility!",
        },
        'az_AZ': {
          'welcome': 'Xoş gəlmisiniz',
          'appName': "N9 DESTINY HUB",
          'appSlogan':
              "Sizin Xoşbəxtlik, Sevgi və Bolluq Yolunuz Burada Başlayır:  Şəxsi həftəlik ulduz falını, meditasiya musiqisini və daha çoxunu əldə edin",
          'start': 'Başla',
          'know': "Gəlin bir-birimizi tanıyaq",
          'nameQuestion': 'Necə sizi çağıra bilərəm?',
          'name': 'Ad',
          'birthQuestion': 'Hansı tarixdə doğulmusunuz?',
          'birthOfDate': 'Doğum tarixi',
          'timeQuestion':
              'Dəqiq proqnozlar vermək üçün sizin doğum vaxtınızı da bilməliyəm. Əgər bilmirsinizsə, sadəcə 12:00 seçin',
          'time': 'Doğum vaxtı',
          'cityQuestion': 'Doğulduğunuz şəhəri yazın',
          'city': 'Şəhər',
          'wrongEmail': 'Email səhvdir',
          'hello': 'Salam, ',
          'yourMessage': 'Sizə bu həftənin mesajı:',
          'horoscopeToday': 'Həftənin ulduz falı',
          'meditationMusic': 'Meditasiya üçün musiqi',
          'weekNumber': 'Həftənin uğurlu rəgəmi',
          'aries': 'Qoç',
          'taurus': 'Buğa',
          'gemini': 'Əkizlər',
          'cancer': 'Xərçəng',
          'leo': 'Şir',
          'virgo': 'Qız',
          'libra': 'Tərəzi',
          'scorpio': 'Əqrəb',
          'sagittarius': 'Oxatan',
          'capricorn': 'Oğlaq',
          'aquarius': 'Dolça',
          'pisces': 'Balıqlar',
          'meditationInfo':
              'Meditasiya həm emosional rifahınıza, həm də ümumi sağlamlığınıza fayda verə biləcək sakitlik, dinclik və tarazlıq hissi verə bilər. Diqqətinizi sakitləşdirici bir şeyə yönəltməklə istirahət etmək və stresin öhdəsindən gəlmək üçün də istifadə edə bilərsiniz. Meditasiya mərkəzdə qalmağı və daxili dincliyi qorumağı öyrənməyə kömək edə bilər.Və bu faydalar meditasiya sessiyanız bitdikdə bitmir. Meditasiya sizi gün ərzində daha sakit keçirməyə kömək edə bilər. Və meditasiya müəyyən tibbi vəziyyətlərin simptomlarını idarə etməyə kömək edə bilər.',
          'readMore': 'Ətraflı oxu',
          'quit': 'Çıxış et',
          'rulingPlanet': 'Baş planet:',
          'tarotCard': 'Tarot kartı:',
          'element': 'Element:',
          'askQuestion': 'Bölüşün bizimlə...',
          'comments': 'Şərhlər',
          'noComment': 'Şərh yoxdur...',
          'writeComment': 'Şərh bildirin',
          'noInfo': 'Xana boş qala bilməz',
          'length': 'Simvol çatışmır',
          'description': 'Təsvir',
          'love': 'Sevgi',
          'character': 'Xasiyyət',
          'health': 'Sağlamlıq',
          'compatibility': 'Uyğunluq',
          'privacyPolicy': 'Gizlilik şərtləri',
          'suggestions': 'Təkliflər və iradlar',
          'rules': 'Paylaşım qaydaları',
          'back': 'GERI',
          'read': 'Oxudum',
          'socialMedia': 'Sosial şəbəkələrmiz',
          'validName': 'Ad düzgün daxil edilməyib',
          'validCity': 'Şəhər adı düzgün daxil edilməyib',
          "select_zodiac": "Bürc seçin",
          "next": "Növbəti",
          "statistics_heading":
              "İstifadəçilərimizin 90%-i gündəlik bürclərinin həyatlarına daha çox təsir etdiyini söylədi",
          "statistics_title":
              "Bu tətbiq səhərlərimi tamamilə dəyişdi! Əvvəllər günümü tələsik keçirirdim, amma indi hər səhər bürcümü yoxlayaraq başqalarının nə dediklərini oxuyuram. Bu, mənə daha tarazlı və sakit hiss etməyə kömək edir.",
          "statistics_subtitle":
              "Minlərlə başqalarına qoşul və bu gün bizimlə yolculuğuna başla.",
          "check_love": "Sevgi Uyğunluğunuzu Yoxlayın!",
          'birthdate_register':
              "Sizə fərdi ulduz falı təqdim etmək üçün doğum tarixinizi bilməliyik, bu da günəş bürcünüzü müəyyən etmək üçün vacibdir",
          "explore_with_tests":
              "Marağlı testlərimizlə sevgi uyğunluğunuzu araşdırın",
          "me": "Mən",
          "lover": "Sevgilim",
          "check_compatibility": "Uyğunluğu yoxla",
          "aries_aries_message":
              "Onlar 91% uyğundur. Onlar eynidirlər, amma bir məqam var: hər biri öz cinsi rolunu o qədər parlaq şəkildə göstərir ki, tamamilə fərqli görünürlər.",
          "aries_aries_love":
              "Onların arasında sevgi anidən, gözlənilmədən alovlanır. Yanğından xilasetmə təlimatlarında onların sevgisinin qaydaları “Xüsusi hallarda” bölməsində təsvir olunardı, çünki burada hər şey maksimum dərəcədə qızğın keçir. Hər ikisi də alovlanmağa meyllidirlər və məhşur sevgi alovu çox vaxt ağılı tamamilə yandırır. Hər ikisinin də. Əgər Qadın-Qoç və Kişi-Qoç baxışlarla qarşılaşıblarsa, bir neçə metr radiusunda olan hər kəs elektrik naqillərinin qapanması zamanı baş verən səslərə bənzər səslər eşidərdi. Qığılcımlar da olardı. Ümumilikdə, bu iki insanın sevgisi ehtiras və gözlənilməzliklə doludur, amma nəvaziş azdır (baxmayaraq ki, onların nəvazişi bir az fərqlidir, buna necə deyərlər, aktiv, qızğın nəvaziş, belə bir nəvaziş-lava), biz onu başa düşdüyümüz mənada isə demək olar ki, sabitlik yoxdur. Amma hər şey maksimum dərəcədə dürüstdür: heç bir gizli niyyət və ya başqa yerə baxış yoxdur. Onlar hər ikisi də yalnız bir-birini istədiklərini bilirlər. Amma...",
          "aries_aries_family":
              "Onların evliliyi çox parlaq və etibarlı olacaq. Elə bil necə ola bilər ki, bu iki şey bir araya gəlsin? Amma, bax elə belə də olur. Əgər iki Qoç qərara gəliblər ki, onlar həyatlarının sonuna qədər birlikdə olmaq istəyirlərsə, o zaman... Yəqin ki, onlar bu müddətlə bağlı tələskənlik ediblər. Məsələ ondadır ki, onlar bu uzun məsafəni mütləq keçməyəcəklər demək deyil, amma saçlarına ağ düşməmiş, təbiətləri onları bu yoldan daha tez çəkindirə bilər, siz başa düşdünüz. Onların evliliyində əsas məsələ, uzaq perspektivləri əhatə edən vədlər verməməkdir. Qoy hər şey öz axarı ilə getsin, çünki ən yaxşı halda bu, ömür boyu davam edəcək, əslində isə iki ömür boyu, iki parlaq Qoçun iki parlaq həyatı boyu. Yeri gəlmişkən, onlar əla valideyn olacaqlar: təxmin edin, 'Ana, ata və mən - idman ailəsi' kimi müsabiqələrdə ilk yerləri kim tutacaq?.. Bəli, düzgün təxmin etdiniz.",
          "aries_aries_friendship":
              "Qoçlar arasında dostluq sədaqət və sabitliklə seçilir. Sevgi münasibətlərindən fərqli olaraq, dostluq iki Qoça sakitliyi qorumağa imkan verir. Burada münasibətləri məhv edə biləcək ehtiras və həyəcan olmayacaq. İki Qoç bir-birini yarım sözdən, daha dəqiq desək, yarım jestdən anlayacaq. Qoç dostları süni davranmayacaqlar - onlar sadəcə pizza sifariş edib, pivə içib, ürəkləri istəyən kimi əylənəcəklər. Bu zaman artıq onların kiminsə qadın, kiminsə kişi olmasının heç bir əhəmiyyəti olmayacaq. İki Qoçun dostluq görüşləri ani və epizodik xarakter daşıyacaq – bu, impulsiv, amma eyni zamanda yaxşı, uzunömürlü dostluq olacaq.",
          "aries_aries_business":
              "Onlar hər ikisi çox düşünməyi sevmir, qərarları tez – bəzən hətta çox tez qəbul edirlər. Qoçların işləri kifayət qədər yaxşı gedə bilər, əgər hər ikisi kənardan dəstək alarlarsa. Onlara üçüncü biri lazımdır – daha düşüncəli, daha səbirli biri. Qoç qadın və Qoç kişi gözləməyi sevmir, pul və irəliləyiş arzusundadırlar. Nəticəyə həddindən artıq yönəlmə onları pis vəziyyətə sala bilər: böyük məqsədlərə çatmaq üçün iki Qoç özlərini tükədə bilər, çünki geri dönüş yolu üçün qüvvələrini əsirgəməyiblər. Onların birgə işinin üstünlüyü – inkişaf arzusunun çox olması və yüksək iş qabiliyyəti, çatışmazlığı isə – səbirsizlik, detallara diqqətsizlik və diplomatiyanın olmamasıdır.",
          "aries_taurus_message":
              "Uyğunluqları 81%-dir. Qız onun yanında parlaq və aktiv qala biləcək, oğlan isə ləng, amma inadkar olacaq. Qızın xarici gücü ilə oğlanın daxili inadkarlığı qarşılaşdıqda, iki inadkar insanın səssiz mübarizəsi başlayır. Daha sonra onlar bir-birinə aşiq olurlar və mübarizə daha da maraqlı olur.",
          "aries_taurus_love":
              "Qadın-Qoç və Kişi-Buğa\nOnlar bir-birini güclü, incə və əbədi şəkildə sevə bilərlər. Kişi-Buğaya qadının enerjisi cəlb edəcək, bəzən özündə çatışmayan (və ya gizlətdiyi, çox vaxt özü də bunu qəbul etmədiyi) enerji olacaq. Qadın isə kişinin ona verdiyi sabitliyi tapacaq, amma bu sabitlik ona yetərli olacaqmı? Əvvəlcə belə görünə bilər, amma zamanla bu sabitlik və hətta monotoniya onu ağlından çıxara bilər. Kişi-Buğa isə qadının impulsivliyindən əsəbləşəcək – gücünü niyə belə israf edir, düşünəcək.\nQadın gücünü israf edir, kişi isə qənaət edir. Qadın ona duyğularını əsirgəmədən verir, kişi isə sakit olmağı üstün tutur. Qadın onun qətiyyətsizliyinə inciyir, kişi isə başa düşmür. Qadın-Qoç və kişi-Buğa arasındakı münasibətləri tam dəqiq təsvir etmək üçün Adriano Çelentano ilə “Meymunu zapt etmək” filmini xatırlamaq kifayətdir. Dəyişən şərhlər lazım deyil.\n\nQadın-Buğa və Kişi-Qoç\nQadın-Buğa kişi-Qoça tez-tez qalib gəlməsi lazım olan şəxs kimi görünür. Kişi bunu dərhal başa düşmür, yalnız qadın onun bütün iştahlarını pozduqda və onu aldatmaq üçün qurduğu planları dağıtdıqda anlar. Qadın-Buğa bəzən çox həssas və incə olur – kişi-Qoçun çatışmayan şeylərə sahib olur kimi görünür. Kişi israf edir, qadın isə saxlayır; o tələsir, qadın isə qəsdən gecikir; kişi müdafiəni aşmaq istəyir, qadın isə yüksək bir divar tikir.\nOnların münasibətləri dolğun sevgiylə dolu ola bilər, əgər hər iki tərəf bir-birini istəyəcək və bir-birinə güzəştə gedəcək. Qadın-Buğa daha açıq və daha az qətiyyətli olacaq. O, kişi-Qoçu qəbul edəcək və kişi-Qoç daha səbirli olacaq, hətta gözləməyi öyrənə bilər. Qadın-Buğa həqiqətən uzun müddət hazırlananlardan biridir.",
          "aries_taurus_family":
              "Qadın-Qoç və Kişi-Buğa\nƏlbəttə, onlar evlənə bilərlər. Rəsmi şəkildə münasibətlərin tənzimlənməsində kim daha çox maraqlı olacaq demək çətindir, amma çox güman ki, qadın-Qoç olacaq. Qadın-Qoç həmişə və hər şeydə birinci və tək olmaq istəyir (bu, hər qadına xasdır, amma bu xüsusi qadına daha çox). Ona görə də, kişi-Buğa üzərindəki hüquqlarını yüksək səslə, dəqiq və çox güman ki, tezliklə bəyan edəcək. Ailə həyatı istədiyi qədər sadə olmayacaq: temperamental fərqlər tezliklə özünü göstərəcək.\nAncaq kişi-Buğanın təbii səbirli olması hər hansı bir mübahisəni yumşalda bilər, ailə üçün uzun müddət narazılığını ifadə etməz. Onun əksinə, qadın-Qoç yaranan mübahisənin mahiyyətini dərhal aydınlaşdırmaq istəyir. O, onun reaksiyalarına daha diqqətli olmalı, qadın-Qoç isə daha mülayim olmalıdır. Əgər onlar çalışsalar, uzun və xoşbəxt həyat sürə bilərlər.\n\nQadın-Buğa və Kişi-Qoç\nOnların evliliyi çox mümkündür, çünki hər ikisi də başladığı işi bitirməyi sevir. Qadın-Buğanın yüksək maddi rifah istəyi kişi-Qoça tam aydın olmasa da, o kişi kimi buna uyğun gəlməyə çalışır. Onların evlilik birliyi kişinin inkişafına, kişi kimi böyüməsinə xidmət edir. Qadın isə belə bir təminatçı və ailə başçısına sahib olduğunda, həyat səviyyəsi ilə daim razı qalacaq.\nOnların uşaqları anadan bütün lazımlı şeyləri alacaq və atadan güclü və təşəbbüskar böyüyəcəklər.",
          "aries_taurus_friendship":
              "Qadın-Qoç və Kişi-Buğa\n\nƏgər qadın-Qoç və kişi-Buğa dost olarsa, çox güman ki, o, ona qadınlarla necə davranmalı olduğunu məsləhət görəcək. Kişi isə onu sakitləşdirəcək və onun düşüncə, hərəkət və ideyalarını istiqamətləndirəcək. O, onu emosional azad olmağa və etibar etməyə öyrədəcək, kişi isə onu daha az impulsiv və ağıl ilə düşünməyə kömək edəcək. Onlar telefonla danışacaq və vaxt-vaxtı ilə “Deyirdim!” və “Bunu bilirdim!” deyə sərf edəcəklər – əlbəttə, heç biri bir-birini diqqətlə dinləmir.\nO, parıltı axtarır, o isə sakitliyi. Onların arasında heç bir münaqişə yoxdur – buna görə də qadın-Qoç və kişi-Buğa arasındakı dostluq çox uzun sürə bilər.\nQadın-Buğa və Kişi-Qoç\n\nOnlar hər zaman bir-birini dəstəkləyə bilərlər: qadın-Buğa və kişi-Qoç dostluq və tanışlıqlara oxşar baxışlara sahibdirlər. O, ona hər döyüşdən sonra gücünü bərpa etməyə kömək edəcək, kişi isə ona hər şeyin öhdəsindən gəlmək üçün özünə güvənməyə və kifayət qədər enerji olacağına inandıracaq. Əgər onların birgə idman fəaliyyətləri olsa, bu çox yaxşı olar: hər ikisi də bədənlərini hiss etməyi çox sevir.\nMeşəyə yürüşlər, birgə qaçışlar və hər şey haqqında uzun söhbətlər – onlar bir-birinin yanında olmaqdan həqiqətən zövq alacaqlar.",
          "aries_taurus_business":
              "Qadın-Qoç və Kişi-Buğa\nO, yeni işə başlayır, o isə nə qədər resurs lazım olduğunu hesablayır. Onlar ideal işgüzar tərəfdaşlardır. Onun irəliləyişə olan ehtirası və onun hər şeyi “ağılla” etmək istəyi onlara uğur qazanmağa kömək edir. Belə bir ittifaqın mənfi tərəfi odur ki, hər ikisi də maddi tərəfə çox diqqət yetirə bilər və işin irəliləməsi üçün lazım olan ideyalardan məhrum ola bilərlər.\nQadın-Qoç və kişi-Buğa “burada və indi” prinsipi ilə düşünürlər, buna görə də tez-tez hadisələrin necə inkişaf edəcəyini hesablaya bilmədikləri üçün səhv qərarlar qəbul edə bilərlər. Digər tərəfdən, bu, iki materialist arasında olduqca funksional bir ittifaqdır, onların birindən (və ya birindən) biri məhz materializmə inanır.\n\nQadın-Buğa və Kişi-Qoç\nQadın-Buğa və kişi-Qoç biznes sahəsində ən cəsarətli xəyallarını həyata keçirə bilərlər: kişi layihəyə həyat vermək üçün kifayət qədər təşəbbüskar, qadın isə bu layihənin gəlir gətirməsini təmin edə bilər. Bu cütlükdə o, strateqdir, o isə taktik: kişi-Qoç ümumi planlar qurur, qadın-Buğa isə istədiyi nəticəyə çatmaq üçün metodları düşünür və axtarır. Belə bir işgüzar ittifaqın yeganə mənfi tərəfi ideya və ilhamın çatışmazlığı ola bilər.\nAncaq bunun üçün həmişə hava əlamətlərinin nümayəndələrinə müraciət etmək olar.",
          "aries_gemini_message":
              "Uyğunluqları 72%-dir. Qadın odlu, kişi isə hava əlamətidir. Kişi qadına daha da alovlanmağa kömək edə bilər, ya da əksinə, onun alovunu söndürə bilər. Kişi qadını təbii ki, yandırmayacaq, amma qadın kişinin yaddaşında uzun müddət qalacaq.",
          "aries_gemini_love":
              "Qadın-Qoç və Kişi-Əkizlər\nQadın-Qoç və Kişi-Əkizlər arasındakı münasibətləri çox yaxın və dərin adlandırmaq olmaz. Qadının od elementi onun tez alovlanıb eyni dərəcədə sürətlə sönəcəyini bildirir, kişinin hava elementi isə onun yüngül və dəyişkən olduğunu göstərir. Bu qısa müddətli hisslər və emosiyalar onların ortaq xüsusiyyətləridir. Münasibətlər qeyri-ciddi deyil, amma həmişə bir dərəcədə səthi olacaq. Bu, kişi-Əkizlər üçün ideal variant ola bilər.\nAmma qadın-Qoç belə münasibətlərdən hər zaman tam razı qalmayacaq. O, nə qədər tez sönsə də, alovlananda sürətlə hərəkət edir və alovlu etiraflar zamanı kişini yanında görmək istəyir. Kişi-Əkizlər isə əslində Fiqaro kimidir. O, qadın-Qoç alovlu etiraflar istədiyi zaman yanında olmayacaq. Bu münasibətlər mürəkkəb və qeyri-standart olsa da, qadın-Qoçun böyük istəyi ilə bu layihə davam edə bilər.\n\nQadın-Əkizlər və Kişi-Qoç\nQadın-Əkizlər və kişi-Qoç arasındakı münasibətlər sakit və dinc ola bilməz. Qadın-Əkizlər yalnızca günahsız bir qoç kimi görünə bilər. Kişi-Qoçla qadın-Əkizlər, əslində, 'qadınlıq' xüsusiyyətlərini nümayiş etdirir: ondan qaçır, nevrləri gıcırdadaraq, bir mövzuya (və ya bir insana) diqqət yetirə bilməməsi ilə. Bütün bunlar kişi-Qoçu qıcıqlandırır, amma o, geri çəkilmək fikrində deyil.\nOnun hər bir tələsi (yaxud belə olması da mümkündür) yalnız onu daha da qızışdırır, özünü göstərmək üçün: istəyərsə, onu tutub özünə bağlayacaq. Bu cür təqib hər iki tərəfi qızışdırır, amma daha çox kişi-Qoçun xoşuna gəlir. Qadın-Əkizlər rahatlamaq və sevginin yüngüllüyündən zövq almaq istəyər, amma kişi-Qoçla belə bir şey mövcud deyil. Demək olar ki, qadın-Əkizlər və kişi-Qoç arasındakı münasibətlər əsasən kişiyə - onun təşəbbüsünə və inadkarlığına əsaslanır.",
          "aries_gemini_family":
              "Qadın-Qoç və kişi-Əkizlər\nEvli olduqda, Qadın-Qoç və kişi-Əkizlər mübarizələrini davam etdirəcəklər: qadın onun tam mülkiyyət hüququnu müdafiə edəcək, kişi isə onun sərbəstliyini məhdudlaşdırmağa cəhdlərə qarşı çıxacaq. Kişi, evliliyi sərbəstliyə və dəyişikliklərə olan sevgisini məhdudlaşdıran bir şey olaraq qəbul etməyəcək. Ümumiyyətlə, bu ailədə kifayət qədər atəş və fantaziya olacaq — qadın onun atəşini təmin edəcək, kişi isə öz yaradıcılığı ilə.\nƏgər onların uşaqları olacaqsa, heç vaxt darıxmayacaqlar. Qadın-Qoç və kişi-Əkizlər ayrılmaq və yenidən birləşmək, hətta boşanmaq da ola bilər, və evliliyi qorumaq üçün əsasən qadın-Qoçun səyləri olacaq.\n\nQadın-Əkizlər və kişi-Qoç\nƏgər onlar evlənərlərsə, kişi-Qoç daim diqqətdə olacaq: o, yüngül xarakterli həyat yoldaşını hər şeyə qarşı qısqanacaq. Bu, qadın-Əkizlərə bəlkə də xoş gələ bilər, amma çox deyil; o, sərbəstliyi sevir və təzyiqdən xoşlanmır. Kişi-Qoç isə təzyiq etmədən dayanmır, bu səbəbdən qadın-Əkizlər üçün bu evlilik çətin olacaq, çünki onunla həddindən artıq təsir edən bir şəxs arasında yer paylaşmaq məcburiyyətində qalacaq.\nO, bu təzyiqə uzun müddət dözə biləcəkmi, bəlli deyil, amma böyük sevgi və ya ortaq uşaqlar varsa, onların evliliyi uzun müddət davam edə bilər.",
          "aries_gemini_friendship":
              "Qadın-Qoç və kişi-Əkizlər\nOnların dostluğu eyni anda həm yüngül, həm də maraqlı olacaq. Qadın-Qoç ona enerjilərini və emosiyalarını verəcək, o, isə onun üçün əyləncə gətirəcək. Birlikdə barlarda gəzə bilər və bir-birinə yeni tanışlar tapmağa kömək edə bilərlər; qısacası, onlar kişi və qadın arasında mövcud olduğu iddia edilən dostluğu həyata keçirə bilərlər.\n\nQadın-Əkizlər və kişi-Qoç\nQadın-Əkizlər həmişə Kişi-Qoç-a məsləhət verəcək: ən mürəkkəb (o cümlədən etik baxımdan çətin) vəziyyətlərdən çıxış yolunu tapacaq, onu ruhlandıracaq, emosional baxımdan təzələyəcək. O, öz növbəsində, ona özünə inam hissini aşılayacaq, o zəif olduğu zaman kömək edəcək. Qadın-Əkizlər və Kişi-Qoç uzun müddət bir-birlərini dəstəkləyə bilərlər — bu, məhz əsl dostluq adlanır.",
          "aries_gemini_business":
              "Qadın-Qoç və kişi-Əkizlər\nBirlikdəki layihələri çox müvəffəqiyyətli ola bilər, çünki iki səbəbdən: Birincisi, kişi-Əkizlər insanların nə istədiyini mükəmməl anlayır. O, sərfəli müqavilələr və təkliflərə əla duyğuya sahibdir. O, populyar və tələb olunan bir şey yarada bilər. İkincisi, qadın-Qoç layihəyə enerji qatacaq, layihə sanki güclü bir generator kimi onun enerjisindən bəhrələnəcək.\nTəhlükəli bir məqam isə budur ki, kişi-Əkizlər şəxsi maraqları naminə həqiqəti gizlətməyə meyllidir, qadın-Qoç isə yalanı bağışlamır. O, bütün münasibətlərdə – işgüzar münasibətlərdə də – tam şəffaflıq tələb edir. Amma əgər o, sahib olduqlarını qiymətləndirərsə, onların biznesi kifayət qədər güclü ola bilər.\n\nQadın-Əkizlər və Kişi-Qoç\nBirlikdə işləyirlərsə, onların birliyi çox uğurlu ola bilər. Kişi-Qoç-un enerjisi genişdir, o, hər kəsi öz dinamizmi ilə yükləyə bilər, Qadın-Əkizlər isə öz içdən gələn qaynaqlardan müntəzəm həyəcanla paylaşar. Onlar demək olar ki, hər hansı bir işlə məşğul ola bilərlər, amma sabitlik və detallı işləmə məsələlərində başqa birinə ehtiyac duyacaqlar.\nKim onların başlatdığı işi sona çatdıraraq planlarını və ideyalarını reallaşdıra biləcək və bəlkə də gəlir gətirəcək.",
          "aries_cancer_message":
              "81% uyğunluq. O - parlaq və dikbaş, o isə qərarsız və həssas. Elə bil ki, onlar bir-biri üçün məhz lazım olanlardır. Əlbəttə, mübahisələrdən qaçmaq mümkün olmayacaq, amma barışmaqları o qədər şirin olacaq ki, bu mübahisələri belə sevməyə başlayacaqlar.",
          "aries_cancer_love":
              "Qadın-Qoç və Kişi-Xərçəng\nBu, tipik bir cütdür, burada kişi idarə olunan tərəfdir. Qadın münasibətlərin xarici tərəfini idarə edir: tanışlığı başladır, davam etdirir və nə istəyirsə, onu əldə edir. Elə bil ki, hər şeyi kişi edir (axı, kişidir), amma əslində belə deyil. Qadın-Qoç belə bir birlikdə daha çox hakimiyyətə sahib olur, çünki Kişi-Xərçəng sakitcə idarəçiliyi ona verir.\nƏlbəttə, bu, onun tərəfindən bir növ hiylədir: Kişi-Xərçəng qadından gələn həddindən artıq zorakılığı qəbul etməz və kobudluğu, ağılsızlığı sevmir. Bu münasibətlərdə Qadın-Qoç, özü belə bilmədən, sevimli Kişi-Xərçəngin nazını çəkir. Ona elə gəlir ki, o, kişini öz iradəsinə tabe etdirir. Nəticə olaraq, Kişi-Xərçəng bu vəziyyəti bəyənib, öz Qoçunu axtarmağa başlayır.\n\nQadın-Xərçəng və Kişi-Qoç\nBəli, Qadın-Xərçəng və Kişi-Qoç arasında adətən məhz sevgi yaranır. Daha dəqiq desək, bu sevgi tipik Kişi-Qoç və Qadın-Xərçəng arasında baş verir. Bu, zəriflik və güc birliyidir, amma hər şey o qədər də hamar və şirin deyil. Ona sakit bir liman daha çox xoş gəlir: yumşaq örtüklər və bitki çayı, amma Kişi-Qoç daha çox ekstrem və münasibətlərdə 'emosional dalğalanmalar' tələb edir. O, daha çox sakitlik və sabitlik istəyir, amma o isə qadından müəyyən dərəcədə dəyişkənlik gözləyir.\nQadın-Xərçəng bunu qəbul edə bilməz: Xərçəngdən daha sabit və sadiq bir bürc yoxdur. Əgər Xərçəng qadındırsa, vəziyyət milyon dəfə daha da mürəkkəbləşir. Onunla bir az (ya da çox) darıxdırıcı olacaq, ona isə Kişi-Qoçla sakit olmayacaq.\nAmma hələ evli olmadıqları müddətcə, Qadın-Xərçəng dözəcək, amma sonra... Bu arada, öhdəliksiz münasibətlər (yəni sevgi) Kişi-Qoç üçün çox sərfəli olacaq: o, həm azadlıq, həm də müəyyən dərəcədə gözlənilməzlik əldə edəcək (Xərçənglə gözlənilməzlik haqqında danışmaq olarsa), həm də yenidən və yenidən qazanmaq üçün mübarizə aparmalı olacaq - bu isə Kişi-Qoçun ən çox sevdiyi şeydir. Qısacası, çox ehtiras olacaq, amma bu, Xərçəngin ürəyinə lazımdırmı?",
          "aries_cancer_family":
              "Qadın-Qoç və Kişi-Xərçəng\nOnlar evlənə bilərlər və bunun üçün ən azı iki səbəb var: onun sabitlik və proqnozlaşdırıla bilən bir həyat tərzinə can atması və onun sevdiyini itirməmək istəyi. Qadın-Qoç üçün bu nikahda olmaq ona əziz olan birini “özünə saxlamaq” deməkdir. O, hamıya deyir: 'O, mənimdir.' Kişi-Xərçəng isə: 'Biz ailəyik.' deyir.\nOnların mütləq mübahisələri olacaq - lakin bu, məhz münasibətlərin dadını saxlamaq üçün lazım olan 'ədviyyatdır'. Qadın-Qoç və Kişi-Xərçəng bir-birinə təkbaşına əldə edə bilməyəcəkləri şeyləri verə bilərlər.\n\nQadın-Xərçəng və Kişi-Qoç\nƏgər onlar evlənməyə qərar veriblərsə, bu evlilik uzun müddət davam edə bilər. Çünki Qadın-Xərçəng ümumiyyətlə, bir həyat yoldaşı ilə uzun ailə həyatı qurmağa yönəlib. Amma Kişi-Qoç daha çox sevgili axtarır, yoldaş deyil. Onlar görüşərkən Qoç üstünlükdədir, amma Qadın-Xərçəng barmağına üzük taxıldıqdan sonra, Kişi-Qoç idarəni ona təslim edir.\nBu evlilikdə ən böyük çətinlik budur: Kişi-Qoç könüllü şəkildə təslim olanda, Qadın-Xərçəng onun əvvəlki marağını və hisslərini qoruyub saxlamaq çətinliyi ilə üzləşir. Bu, ümumdünya problemi olsa da, Qadın-Xərçəng və Kişi-Qoç cütlüyündə bu, xüsusilə aydın şəkildə özünü göstərir. Lakin Qadın-Xərçəng özünə marağı artırmaq üçün məqsədyönlü addımlar atarsa, möhkəm bir ailə qurmağa müvəffəq olacaq və o, yaxşı bir ər, qadın isə mükəmməl bir yoldaş olacaq.\nBu evlilik daha çox Qadın-Xərçəngin səylərinə əsaslanacaq. Bəlkə də bu pis deyil: bu, tipik bir ailə modelidir, burada qadın emosional mərkəzdir, kişi isə bu məsələlərdə öz qeyri-kamilliyini qəbul edərək, qadının təklif etdiyi qaydaları və, desək də, tələbləri yerinə yetirir.",
          "aries_cancer_friendship":
              "Qadın-Qoç və Kişi-Xərçəng\nOnların arasında yaxın dostluq qurmaq çox çətin olacaq – məsafəni saxlamaq bacarıqları yoxdur. Bu, ya hər şey, ya da heç nə deməkdir. Ya onlar sevgili olurlar, ya da ümumiyyətlə ünsiyyət qurmurlar. Niyə belədir? Çünki onlar bir-birinə çox cəzb olunurlar, özlərini saxlamaq isə sadəcə olaraq mənasız olar. Yəqin ki, onlar adi dostların etdiyi kimi ümumi mövzularda danışmaqda çətinlik çəkəcəklər – Qadın-Qoç və Kişi-Xərçəng daha yaxın, daha sıx bir əlaqə istəyirlər, buna görə də onlar dostluq sərhədlərini tez genişləndirəcək və ya tamamilə yox edəcəklər.\n\nQadın-Xərçəng və Kişi-Qoç\nQadın-Xərçəng və Kişi-Qoç arasında ya çox güclü dostluq olacaq, ya da heç olmayacaq. Düzünü desək, bu, elə bir vəziyyətdir ki, heç kim onların niyə hələ də görüşmədiyini başa düşmür. Heç kim inanmır ki, onlar münasibətləri olmadan dost qalırlar. Qadın-Xərçəng bu yorulmaz ədalət savaşçısını həmişə anlayacaq, ona danışmaq imkanı verəcək, o sözlərini seçib duyğularını ifadə etməyə çalışarkən, tələsməyəcək.\nKişi-Qoç isə həmişə köməyə gələcək, onu kənar hücumlardan qoruyacaq, onun heç arzulamadığı şeylərə necə nail olmaq mümkün olduğunu izah edəcək. Bu bir qədər qəribə bir dostluqdur: onlar bir-birlərinə yalnız təkbaşına həll edə bilməyəcəkləri problemlərlə qarşılaşdıqları zaman ehtiyac duyacaqlar. Ola bilər ki, illərlə dostluq edəcəklər, sonra başa düşəcəklər ki, bu sevgi imiş. Yaxud da heç vaxt anlamayacaqlar.",
          "aries_cancer_business":
              "Qadın-Qoç və Kişi-Xərçəng\nQadın-Qoç və Kişi-Xərçəngin əməkdaşlığının ən böyük üstünlüyü onun nəticəyə fokuslanması və onun əldə olunanları qorumağa meylli olmasıdır. O, arxa cəbhədə işləyəcək, o isə ön cəbhədə. Qadın-Qoç növbəti nailiyyətləri üçün enerjisini Kişi-Xərçəngdən alacaq, o isə onun məqsədyönlülüyündən güc alacaq. Lakin bu 'ideal' mənzərəni pozan iki mənfi cəhət var: onun məsuliyyətsizliyi və onun impulsivliyi.\nAmma əgər Qadın-Qoç bütün mühüm qərarları özü qəbul edərsə, problem yaranmayacaq. Kişi-Xərçəng isə ona təhlükələr haqqında xəbərdarlıq edəcək və döyüşdən əvvəl və sonra onu rahatladacaq.\n\nQadın-Xərçəng və Kişi-Qoç\nKişi-Qoç və Qadın-Xərçəng birlikdə həqiqətən işləyən bir iş təşkil edə bilərlər. O, təşəbbüskar olacaq, o isə toplanılanları qoruyan və detalları işləyən biri. Kişi-Qoç Qadın-Xərçəngi pula və işə daha cəsarətli yanaşmağa təşviq edəcək, o isə ona işgüzar münasibətləri necə sakit və sabit şəkildə idarə etməyi göstərəcək. Bu ikisi birlikdə istənilən ideyanı reallığa çevirə biləcəklər.",
          "aries_leo_message":
              "Uyğunluq: 97%. Hər ikisi Od ünsürünə mənsubdur: parlaq və enerjili, tez alovlanır və tez sönürlər.",
          "aries_leo_love":
              "Qadın-Qoç və Kişi-Şir\nQadın-Qoç, özününki kimi nəcib birini arzulayanda, bəlkə də fərqinə varmadan Kişi-Şirin obrazını canlandırır. O, zərifdir, təravətlidir və onun qəlbini qazanmaq üçün nə qədər lazımdırsa, mübarizə aparmağa hazırdır. Qadın-Qoç tez təslim olanlardan deyil, hər ikisi belə bir oyundan zövq alır. Onlar cansıxıcı olmayacaqlar: həm qadın-Qoç, həm də kişi-Şir münasibətlərə başdan-ayağa dalırlar, sevgi obyektindən başqa heç kimi görmürlər. Onların münasibətlərində əsas problem qısqanclıq olacaq: hər ikisi öz malı kimi qorumağı sevir.\nQadın-Qoç Kişi-Şiri qısqanacaq, çünki o, cəmiyyətdə özünü göstərməyi sevir. O, əsəbiləşəcək – o isə ona heyran qalacaq. O, qapını çırpıb qürurla çıxacaq, o isə onun ardınca qaçacaq. Və çatacaq. Deyəsən, onlar bütün ömürlərini belə keçirə bilərlər.\n\nQadın-Şir və Kişi-Qoç\nQadın-Şir və Kişi-Qoç dərhal bir-birinə aşiq olurlar. Yaxşı, o dərhal, o isə ardınca. Onların sevgisi ehtiraslı, parlaq və çox canlı olacaq. Bu sevgidə duyğu və hisslərin bütün çalarları üçün yer olacaq və onlar bu hissləri digər tərəfdaşların yanında olduğundan daha açıq şəkildə ifadə edə biləcəklər. Qoç və Şir obrazlarını müqayisə etsək, birincisi hər şeyin başladığı qığılcım, ikincisi isə yavaş-yavaş alovlanan, amma uzun müddət isidən bərabər alovdur.\nKişi-Qoç çox güman ki, tanışlığın təşəbbüskarı olacaq - ona ilk addımı atmaq heç də çətin olmayacaq (və ondan sonra daha min addım atmaq, necə deyərlər), qadın-Şir isə onların hisslərinin möhkəmlənməsini və incə, bir tərəfdən möhkəm, digər tərəfdən isə davamlı olmasını təmin edəcək.",
          "aries_leo_family":
              "Qadın-Qoç və Kişi-Şir\nOnların ailəsi italyan ailəsinə bənzəyəcək. Çoxlu duyğular, az konstruktivlik. Onlar bir-birini nə qədər çox tanısalar, mübahisələri bir o qədər sakit olacaq, amma ailə həyatının əvvəlində toqquşmalardan qaçmaq olmaz. Qadın-Qoç mütləq qab-qacaq sındıracaq, Kişi-Şir isə öz isterik arvadını sakitləşdirməyə çalışacaq. Onların evlilik həyatından rəngarəng, yüngül bir komediya filmi çəkilə bilər. Hər ikisi elə davranacaq ki, sanki səhnədədirlər.\nUşaqları valideynləri ilə maraqlı anlar keçirəcəklər, lakin bəzən sakitliyə ehtiyacları olacaq ki, bu da Qadın-Qoç və Kişi-Şirin evində nadir bir şeydir.\n\nQadın-Şir və Kişi-Qoç\nƏgər onların münasibətləri kifayət qədər güclü və maraqlıdırsa, evlənməyi gecikdirməyəcəklər. Kişi-Qoç sevimlisini ələ keçirməyi şiddətlə arzulayır - bunun üçün o, münasibətləri rəsmiləşdirməkdə israr edir. Qadın-Şir də onu sevdiklərini və həmişə sevəcəklərini təsdiq etmək üçün həvəslidir. Onların nikahında uşaqlar diqqətlə əhatə olunacaqlar - bəzən həddindən artıq.\nQadın-Şir və Kişi-Qoç ailə həyatında bir qədər emosional sabitliyin çatışmadığını hiss edə bilərlər, lakin bu, yaşla keçməlidir.",
          "aries_leo_friendship":
              "Qadın-Qoç və Kişi-Şir\nQadın-Qoç və Kişi-Şirin dostluğundan danışarkən, bu, çox mümkün olan bir şeydir. Onlar çox bənzəyirlər, oxşar temperamentləri və həyata baxışları var. Qadın-Qoç və Kişi-Şir birlikdə idmanla məşğul ola, yaradıcılıqla məşğul ola, müxtəlif mövzularla bağlı söhbətlər edə bilərlər. Onlar hər ikisi gözləməyi sevmirlər, ona görə də onların ünsiyyəti sürətli, görüşləri isə qısa, lakin dolğun olacaq. Onlar hər ikisi təbiət yürüşlərini və hər cür fiziki fəaliyyəti çox sevirlər.\n\nQadın-Şir və Kişi-Qoç\nOnlar mükəmməl dostdurlar: Qadın-Şir və Kişi-Qoç həmişə söhbət üçün ümumi mövzular tapacaqlar, onlar bir-birini çox bənzədikləri üçün başa düşəcəklər. Onlar eyni musiqiyə aludə ola bilərlər, oxşar arzular və məqsədlərə sahib ola bilərlər. Hər halda, onlar bir-birindən dolub-daşan enerjini alaraq 'doldururlar'. Problemlər qəzəb və digər mənfi hisslərdən qaynaqlana bilər, lakin onlar bu duyğulardan çox tez uzaqlaşırlar.\nTez-tez barışmaq Qadın-Şir və Kişi-Qoçu bir-birinə daha yaxınlaşdırır, onları tamamilə doğmalaşdırır.",
          "aries_leo_business":
              "Qadın-Qoç və Kişi-Şir\nQadın-Qoç və Kişi-Şir işdə yorulmaz əməkdaşlardır. Kişi-Şir işgüzar münasibətlərdə Qadın-Qoçdan daha çox ətraf-mühitə yönəlib. O, iş məsələsində çox tez qərarlar verir. Kişi-Şir onun tabeliyində ola bilər – hər halda, o daha geniş hərəkət edir. İctimaiyyətlə əlaqələr, incəsənət, kütləvi informasiya vasitələri qadın-Qoç və Kişi-Şirin birgə iş üçün çox uyğun sahələrdir.\nOnlar hər ikisi statusa və nüfuza yönəldilib, buna görə də həqiqətən çalışacaq və günəş altında öz yerləri uğrunda mübarizə aparacaqlar. Onlar hətta rəqabətə başlaya bilərlər – axı, yarışmağı sevirlər, bu onlara enerji verir və onları daha canlı və aktiv edir. Onların etməməli olduğu yeganə şey quru hesablamalar və kağızlarla – qiymətli və ya çox olmayan – işdir.\n\nQadın-Şir və Kişi-Qoç\nOnlar nə işlə məşğul olurlarsa olsunlar, o işlər sanki onların əlində “yanacaq”. Kişi-Qoç və Qadın-Şir onlar üçün həqiqətən maraqlı olan bir şey üzərində günlərlə işləməyə hazırdırlar. Birlikdə xüsusilə yaradıcı və ya riskli bir işlə məşğul olurlarsa mükəmməl nəticə əldə edə bilərlər. Onlar parlaqdırlar və məşğul olduqları iş də parlamalıdır.\nÜmumi işlərinin vacib hissəsi komandada xoş bir atmosferin yaradılması və faydalı əlaqələrin genişləndirilməsi olacaq - bunu mükəmməl şəkildə yerinə yetirəcəklər.",
          "aries_virgo_message":
              "Uyğunluq: 84%. Əgər qadın yanğınsa, kişi portativ yanğınsöndürən kimidir. Rahat, praktik və vaxtında.",
          "aries_virgo_love":
              "Qadın-Qoç və Kişi-Qız\nKişi-Qız qadın-Qoç üçün çox rasional və təmkinli görünə bilər. O, gözlənilməz vəziyyətləri və həddən artıq aqressiyanı sevmir, qadın-Qoç isə bunların hamısını özündə cəmləşdirir. Əlbəttə, qadın-Qoç inanılmaz dərəcədə cəlbedicidir və kişi-Qız bunu qiymətləndirir. Amma onun seksual cazibəsi kişi-Qız üçün normadan artıqdır, o, daha azı ilə kifayətlənə bilərdi. Qadın-Qoç bütün məkanı öz varlığı ilə doldurmağa adət edib, o parlaq və ehtiraslıdır, onu görməmək və ya ona laqeyd yanaşmaq mümkün deyil.\nKişi-Qız isə qadının daha yumşaq, mehriban və çox diqqət tələb etməməsini istəyir - o zaman özü bu diqqəti ona göstərəcək. Qadın-Qoç gözləməyəcək, sadəcə istədiyini alacaq - daha dəqiq desək, çalışacaq, çünki kişi-Qız o qədər də asan təslim olan biri deyil. Əgər kişi-Qız itaət strategiyasını seçərsə, uzun müddət buna davam gətirə bilməz, axı o, öz iradəsini boğmağa öyrəşməyib (qadın-Qoçun yanında bunu etmək məcburiyyətində qalacaq).\nƏgər onlar birlikdə olmaq istəsələr, hər ikisinin şəxsiyyətini dəyişdirməsi lazım gələcək - və bu, onların hər ikisinin xəyal etdikləri şey olmaya bilər.\n\nQadın-Qız və Kişi-Qoç\nQadın-Qız və Kişi-Qoçun münasibətləri parlaq, lakin sabit ola bilər. Sabitliyi qadın-Qız, parıltını isə Kişi-Qoç gətirir. Bu, Torpaq və Odun ittifaqıdır — iki ən güclü ünsürün yaradıcı, lakin dayanıqlı birləşməsi. Birlikdə bu iki nəfər çox şeyə nail ola bilər, əsas odur ki, vaxtında bir-birinin yanında olmaq lazım olduğunu başa düşsünlər. Qadın-Qız inamsızlığı və sevgi məsələlərində yüksək skeptisizmi ilə seçilir, buna görə də Kişi-Qoç onu rahatlamağa və özünü buraxmağa inandırmaq üçün çox çalışmalı olacaq.\nKişi-Qoç qarşılıqlı simpatiyanı qazanmaq bacarığına malikdir — özü isə ani olaraq aşiq olur. Problemlər temperament fərqliliyindən yarana bilər: Kişi-Qoç artıq hər şeyə hazır olduğu halda, Qadın-Qız hələ də vəziyyəti düşünüb analiz edir. Onun ürəyinə yaxın qəbul etdiyi şeylər, Qadın-Qız üçün emosional cəhətdən heç bir məna daşımaya bilər.",
          "aries_virgo_family":
              "Qadın-Qoç və Kişi-Qız\nOnların nikah bağlamamalarının əsas səbəbi odur ki, razılığa gəlməkdə çətinlik çəkəcəklər. Qadın-Qoç öz istədiyində israr edəcək, çox vaxt onun istəkləri real vəziyyətlə ziddiyyət təşkil edəcək, kişi-Qız isə normalara və qaydalara əməl edilməsini tələb edəcək. O, reallığa söykənməyə vərdiş edib - bu onun güclü tərəfidir. Qadın-Qoç isə impulsiv hərəkət edir. Ola bilsin ki, onlar bir-birlərini tarazlaşdıra bilərlər.\nOnların nikahda yaşaya bilməsinin yeganə variantı qadın-Qoçun irrasionallığını və sahiblənmə meylini cilovlaması, kişi-Qızın isə öz sürətli və azadfikirli həyat yoldaşının hərəkətlərinə daha dözümlü olmasıdır.\n\nQadın-Qız və Kişi-Qoç\nQadın-Qız və Kişi-Qoç arasında nikah möhkəm və xoşbəxt olacaq. Əlbəttə, onların arasında xeyli sayda münaqişələr olacaq, çünki nə o, nə də Kişi-Qoç partnerini anlamaq və ona uyğun davranmaq üçün kifayət qədər incə həssaslığa malik deyil. Onlar arasında rahatlıq (qadın-Qız bunu təmin edəcək) və ehtiras (bunu isə kişi-Qoç təmin edəcək) olacaq, lakin onlar bəzən qəlbi istiləşdirən bir bağlılıq və sentimentallıq çatışmazlığını hiss edə bilərlər.\nBəlkə də, yaş artdıqca və bir yerdə keçirdikləri illər çoxaldıqca, Qadın-Qız və Kişi-Qoç bir-birinə daha yaxınlaşaraq, həqiqətən də bir-birini hiss etməyi bacararlar.",
          "aries_virgo_friendship":
              "Qadın-Qoç və Kişi-Qız\nQadın-Qoç və kişi-Qızın dostluğu hər ikisi üçün faydalıdır. Qadın-Qoç orada soyuqqanlı hesab tələb olunan yerdə lazım olan dəstəyi alır, kişi-Qız isə ondan emosional olaraq bəhrələnir, onun yanında 'isidir'. Bəlkə də dostluq onların münasibətləri üçün ideal formatdır, çünki kişi-Qıza təhlükəli olan yaxınlıq yoxdur və qadın-Qoçun arzuları təmin edilmir. Onlar illərlə əl-ələ gedə, həyatın çətin anlarında bir-birlərini ovundura bilərlər.\nOnların dostluğunu qorumağa kömək edəcək əsas məsləhət, bir-birinə fikirlərini zorla qəbul etdirməmək olacaq. Yardım könüllü şəkildə qəbul edilməlidir. Qadın-Qoç qaydalı dostuna daha mərhəmətli olmalı, kişi-Qız isə onun gözlənilməzliyinə daha rahat yanaşmalıdır.\n\nQadın-Qız və Kişi-Qoç\nOnların dostluğunda nəsə çatışmırmış kimi hiss oluna bilər. Bəlkə də, yüngüllük. Kişi-Qoç həddindən artıq dramatizasiya meylinə malikdir, Qadın-Qız isə tanınmış bir sinikdir, buna görə də, ehtimal ki, biri digərini hər şeyin itirilmiş olduğu vaxtlarda ruhlandıra bilməyəcək. Kişi-Qoç ruhlandıracaq, Qadın-Qız isə praktiki məsləhətlərlə kömək edəcək — bu, müsbətdir. Ortak maraqlar — bu da müsbətdir. Ancaq qəlbən söhbətlərin çatışmazlığı və dostun ruhunu dərinliklə başa düşməmək — mənfidir. Lakin onlar bir-birinə yaxşı uyğunlaşa bilərlər və o zaman qarşılıqlı anlaşma yeni səviyyəyə çıxar.",
          "aries_virgo_business":
              "Qadın-Qoç və Kişi-Qız\nQadın-Qoç və kişi-Qız yaxşı əməkdaşlıq edə bilərlər. Hər ikisinin yüksək məhsuldarlıq üçün çatışmayan tərəfləri bir-birində var: kişi-Qıza ideya və enerji çatmır, qadına isə məqsədə çatmaq üçün istiqamət və rahat üsullar lazım olur. Əgər onların ümumi biznesi varsa, qadın-Qoç hər ikisini enerji ilə dolduracaq. Kişi-Qız isə detalları işləyib hazırlamaq və sənədlərlə işləmək öhdəliyini öz üzərinə götürəcək - axı bu onun üçün mükəmməl alınan bir işdir.\n\nQadın-Qız və Kişi-Qoç\nQadın-Qız və Kişi-Qoçun birgə fəaliyyəti çox səmərəli olacaq. Torpaq və Odun elementlərinin birləşməsi pragmatik məqsədlərə nail olmaqda yaradıcı yanaşma verir. Bu elm və istehsalat, ticarət və digər sahələr ola bilər. Əsas odur ki, onlar anlamalıdırlar: Kişi-Qoç tərəfdaşlarla münasibətləri qurmağa çalışmamalıdır, Qadın-Qız isə hər şeyi təkbaşına etməyə cəhd etməməlidir.",
          "aries_libra_message":
              "Bu cütlük 83% uyğunluğa sahibdir. Mümkün olan qeyri-standart rolların paylanması — israrlı qadın və itaətkar kişi — onlara uyğun gəlir və bu vəziyyət onlara xoşdur.",
          "aries_libra_love":
              "Qadın-Qoç və Kişi-Tərəzi\nQadın-Qoçun hərəkətlilik və itaət etməmə meyli, Kişi-Tərəzidə qarşılıq tapır. Kişi-Tərəzi qadın-Qoç üçün sevgi və nəzakət nə olduğunu göstərmək üçün sanki yaradılmışdır. Əvvəlcə bir-birilərinə alışmaq çətin olacaq, çünki onlar ziddiyyətli başlanğıcaları təmsil edirlər: qadın-Qoç — aktiv, genişlənən, Kişi-Tərəzi isə — passiv (ən yaxşı mənada). Tanış olduqda, Kişi-Tərəzi maksimum dərəcədə köməkçi davranacaq və ya sadəcə qadın-Qoçun təşəbbüs göstərməsini gözləyəcək.\nO, qadın-Qoçun diqqətini cəlb etməyə belə çalışa bilər, amma özü hərəkət etməyə tələsməyəcək. Qadın-Qoç, bu səmimi kişi ilə nədən bu qədər maraqlandığını anlamaq istəyəcək. İkisi də bir-birinə aşiq olduqlarını başa düşdükdə, hər ikisi də münasibətlərin davamını istəməyə hazır olacaq: qadın-Qoç aktiv şəkildə onun diqqətini qazanmağa çalışacaq, Kişi-Tərəzi isə onu sevdiyi üçün diqqətini ona verəcək.\nBu, kişini qadın kimi təsvir etsə də, əslində Kişi-Tərəzi, istəkli sevgilisinə uyğunlaşmağı mükəmməl bacarır.\n\nQadın-Tərəzi və Kişi-Qoç\nQadın-Tərəzi ilə Kişi-Qoç görüşdükdə, əvvəlcə bir-birilərini başa düşmürlər. Qadın-Tərəzi onun inatçılığından və diplomatik olmamasından narahat olur, Kişi-Qoç isə onun çox yüngül və havadar olduğunu düşünür. Lakin, onlar bir-birilərinə daha dərin baxdıqca, qarşılıqlı maraqları artmağa başlayır. Onların sevgisi spontandır, münasibətlər klassik sxem üzrə inkişaf edir: Kişi-Qoç qadın-Tərəzini qazanmağa çalışır, qadın-Tərəzi isə özünü qazanmağa imkan verir.\nQadın-Tərəzi oynamağı və dözümü sınamağı sevir, Kişi-Qoç isə birbaşa və gözləməyi sevmir. Qadın-Tərəzini romantik Venus idarə edir, Kişi-Qoçu isə ehtiraslı Mars. Onların münasibətləri parlaq anlarla dolu olacaq, darıxmaq mümkün olmayacaq.",
          "aries_libra_family":
              "Qadın-Qoç və Kişi-Tərəzi\nOnların nikahı xoşbəxt olacağı vəd edir. Tamamilə bir-birini başa düşərək, qadın-Qoç və Kişi-Tərəzi güclü bir ailə quracaq. Əlbəttə, münaqişələr də olacaq. Qadın-Qoçun qızğınlığı səbəbindən mübahisələr yaranacaq — Kişi-Tərəzinin diplomatik yanaşması bəzən yetərli olmayacaq. Bu səbəbdən qadın-Qoç qadınlıq keyfiyyətlərini inkişaf etdirməli, güzəştə getməyi öyrənməlidir. Kişi-Tərəzi isə öz fikirlərini müdafiə etmək və müstəqil həyat yoldaşının təzyiqinə qarşı durmaq üçün daha möhkəm olmağı öyrənməlidir.\nNikah onların şəxsi inkişafını təşviq edəcək, bu isə çox faydalıdır.\n\nQadın-Tərəzi və Kişi-Qoç\nOnlar həmişə nikah üçün can atsa da, mütləq nikah etməli deyil. Qadın-Tərəzi sevgini və tərəfdaşlığı arzulayır, Kişi-Qoç isə sevdiyi insanı əldə etmək istəyir. Tez-tez rəsmi münasibətlərin qurulması ehtiras və romantikanı azaldır — bu isə onların ən böyük qorxusudur. Bu ikisi daha çox ömür boyu görüşmək istəyəcək, nikahı seçməkdən çəkinəcək.\nLakin, əgər nikah edərlərsə, hər şey çox yaxşı ola bilər. Qonaq nikahları, mübahisələr və barışmalar, ayrılıqlar və gözlənilən görüşlər — bunlar onların sevgisini saxlamağa kömək edəcək, münasibətləri daha rəsmi olsa belə.",
          "aries_libra_friendship":
              "Qadın-Qoç və Kişi-Tərəzi\nOnlar mükəmməl dostlar ola bilər. Kişi-Tərəzi qadın-Qoçu sakitləşdirəcək və başqaları ilə münasibətləri necə düzəldəcəyinə dair məsləhətlər verəcək. Qadın-Qoç isə ona yeni nailiyyətlərə can atmağa kömək edəcək, ona inam aşılayacaq və çətin anlarda dəstəkləyəcək. Onlar bu münasibətləri qiymətləndirəcək, çünki qadın-Qoç və Kişi-Tərəzi sanki bir bütövün iki yarısıdır. Birlikdə hər şeylə məşğul ola bilərlər, tamamilə bir-birini qəbul edirlər, düzəltməyə çalışmadan.\nOnlar bir-birinə təsir göstərə biləcəklər, amma bu, yumşaq və xoş bir təsir olacaq, daxili etiraz yaratmayacaq.\n\nQadın-Tərəzi və Kişi-Qoç\nBu dostluq dəstəkləyici olacaq. Onlar bir-birinə kömək edə bilər, dostluq münasibətləri hər ikisi üçün əhəmiyyətli olacaq. Qadın-Tərəzi Kişi-Qoça insanlarla münasibətləri necə düzəltməyi göstərəcək, Kişi-Qoç isə ona lazımlı iradə impulsunu verəcək, qeyri-müəyyənliyi aşmağa kömək edəcək. Onlar bir-birinə daha çox ehtiyac duyacaqlar, çünki bu əlaqədə həm enerji, həm də harmoniya mövcuddur. Yəqin ki, onlar hər halda münasibətlərə başlayacaqlar; hər şey çox ideal görünür.",
          "aries_libra_business":
              "Qadın-Qoç və Kişi-Tərəzi\nBirlikdə işlədikdə, hər şey yaxşı olacaq. Qadın-Qoç ümumi işdə mərkəzi fiqur olacaq — onun ideyası ilə hər şey başlayacaq. Kişi-Tərəzi isə onun fikirlərini alacaq, iş üçün lazım olan insanları cəlb edəcək. Yəqin ki, hər ikisi də detallarla çox maraqlanmır — bu məsələdə digər ulduzların nümayəndələri ilə əməkdaşlıq etməli olacaqlar. Hər halda, qadın-Qoç və Kişi-Tərəzi, çox şeyə nail ola biləcək bir komandadır.\n\nQadın-Tərəzi və Kişi-Qoç\nƏgər onlar ümumi iş və ya biznes təşkil etsələr, rollar belə olacaq: qadın-Tərəzi müştərilərlə və tərəfdaşlarla əlaqələr quracaq, Kişi-Qoç isə bazarları, əraziləri, müştəri ağlını və onun görmə sahəsinə düşən hər şeyi fəth edəcək. Bu cütlük birlikdə işdə çox uğurlu olacaq — yenə də, əgər onların iş münasibətləri romantik yükdən təsirlənməzsə.\nAmma niyə romantik yük zərər verməlidir? Qadın-Tərəzi və Kişi-Qoç sevgili və iş münasibətlərini uğurla birləşdirə bilər.",
          "aries_scorio_message":
              "Uyğunluq 76%. Qadın-Qoç uzun müddət gözləməyə vərdiş etməyən və təşəbbüsü öz əlində saxlayan qadınlardandır, kişi-Əqrəb isə qadının açıq və müstəqil şəkildə özünü göstərməsini sevən kişilərdəndir.",
          "aries_scorpio_love":
              "Qadın-Qoç və Kişi-Əqrəb\nHər iki bürc — Qoç və Əqrəb — ehtiraslı Marsın təsiri altındadır (Əqrəb əlavə olaraq daha ehtiraslı Plutonun təsirini də hiss edir), buna görə də aralarındakı münasibətlər çox isti və səmimi olur. Adətən, onlar bir-birilərini tez tanıyırlar: ortada bir alov onları bir-birinə cəlb edir. Tanışlıq dövrü adətən uzun sürmür (buna baxmayaraq, kişi-Əqrəb uzun müddət gərginlik yaratmağı sevir — bu ona daha maraqlı gəlir), bu ikili işləri tez həll edir.\nO, öz açıq-saçıq və dürüstlüyü ilə onu təsirləndirir: məsələn, ilk görüşü özünə təyin edə bilər — o, arzularını yaxşı başa düşür və qərarlı hərəkət edir. Kişi-Əqrəb isə ona rahatlanmağa və dərinlərə enməyə imkan verir: o, hipnoz edərək onları yaxınlaşdıran bir vəziyyət yarada bilər. Münasibətlərində sabitlik çatışacaq — amma kim dedi ki, buna ehtiyacları var?\n\nQadın-Əqrəb və Kişi-Qoç\nQadın-Əqrəb və kişi-Qoç arasındakı münasibətlər çox intensiv olacaq. Onları idarə edən Mars, fəaliyyət, ehtiras və hətta aqressiya planetidir. Buna görə də, onların sevgisi iki ürəyin birləşməsi deyil — daha çox bir müharibə vəziyyətindəki barış müqaviləsi kimi olacaq. Hər ikisi də tərəfdaşını 'ələ keçirmək', onu tamamilə özlərinə tabe etmək istəyirlər.\nƏgər kişi-Qoç açıq şəkildə ələ keçirmək istəyirsə, qadın-Əqrəb ruhunu, şüuraltını özünə tabe etmək istəyir — bədəni o qədər də maraqlı deyil. Onlar fərqli cəbhələrdə mübarizə aparırlar: kişi-Qoç onun diqqətini cəlb etməyə çalışır, açıq və sərt davranır, onu öz yanında olmaq məcburiyyətində qoyur. O isə gizli, ağıllı şəkildə hərəkət edir, kişinin hərəkətlərini öz arzularına uyğunlaşdırmağa çalışır. Hər ikisi də tərəfdaşını tabe edir, amma fərqli üsullarla.\nYaxşıdır ki, hər biri yalnız özünü güclü (kişi-Qoç) və hiyləgər (qadın-Əqrəb) hesab edir.",
          "aries_scorpio_family":
              "Qadın-Qoç və Kişi-Əqrəb\nQadın-Qoç və kişi-Əqrəb tez-tez evlənirlər: onları bir-birinə olan cazibə o qədər güclüdür ki, bir ömür boyu birlikdə yaşamağı qərara alırlar (bəlkə də daha uzun müddət — buna mistik kişi-Əqrəb də əlavə edərdi). Onların ailə həyatının yeganə mənfi tərəfi, kompromislərə getməmə qabiliyyətidir (əslində ailə həyatında kompromis olmadan çox irəliləmək olmaz). Hər ikisi də ehtiraslı və iradəli olduğu üçün, bu, bir İtalyan ailəsi kimi olacaq: səs-küylü mübahisələr və səs-küylü barışmalarla dolu.\n\nQadın-Əqrəb və Kişi-Qoç\nƏgər evlənsələr, onların ailə həyatı sakit bir limanı xatırlatmayacaq. Hər ikisi də emosiyalarını içində saxlamağı sevmir, amma qadın-Əqrəb bu məsələdə daha ağıllıdır. Kişi-Qoç isə tez-tez qıcıqlandırıcı olur — onun həyat yoldaşı olmaq çətin işdir. Kişi-Qoçun daxili gərginliyini başa düşən qadın-Əqrəb, vəziyyəti daha da gərginləşdirməməyə çalışacaq, amma bu onun üçün asan olmayacaq, çünki o, vəziyyəti gərginləşdirməyi sevir.",
          "aries_scorpio_friendship":
              "Qadın-Qoç və Kişi-Əqrəb\nDost qala bilərlər, əgər münasibətləri daha yaxın bir səviyyəyə keçirmək qərarına gəlməzlər. Əgər onlar sevgili olmayacaqlarsa (amma niyə də olmasın?), qadın-Qoç və kişi-Əqrəb əla dostlar ola bilərlər. Əsas odur ki, onlar bir-birinə qarşılıqlı dəstək təmin edə bilərlər. Hər hansı bir vəziyyətdə bir-birinə kömək etməyə hazır olacaqlar.\nSadiqlik — həm qadın-Qoç, həm də kişi-Əqrəb tərəfindən dəyərləndirilən bir keyfiyyətdir, ona görə də onlar həqiqətən sadiq və etibarlı dostlar olacaqlar.\n\nQadın-Əqrəb və Kişi-Qoç\nDost qala bilərlər. Amma onların bir-birində rahatladıcı bir şey tapması çətin olacaq, çünki hər ikisi də daha həssas və anlayışlı tərəfdaşlar axtarır. Kişi-Qoç, onun dinləniləcəyini və stressdən qurtulacağını gözləyəcək, qadın-Əqrəb isə eyni şeyi, əlavə olaraq fiziki qayğını da istəyəcək. Onlar bir-birilərini yaxşı başa düşəcəklər, amma bir-birinə kömək edib-etməyəcəkləri şübhəlidir. Digər tərəfdən, əgər dostluqda yalnız anlayış axtarırsa, məsləhətlər və konkret kömək deyil — bu, mükəmməl uyğun gəlir.\nBu, iki enerjili şəxsin yorulmaz bir birliyidir. Nə iş görsələr, layihə 'yanacaq'. Yorulmaz həvəskarlar olan qadın-Qoç və kişi-Əqrəb hər hansı bir layihəyə lazım olan impulsu verə bilərlər — amma detalların işlənməsi onlara çətinliklə gələcək. Kişi-Əqrəb daha diqqətli və detallı yanaşma tələb edən sahələrdə uğurlu ola bilər, qadın-Qoç isə bu prosesi əsəbiləşdirə bilər.\nAmma əgər məqsəd həqiqətən dəyərlidirsə, qadın-Qoç özünü təşkil edə bilər və lazımi nəticəni əldə edə bilər.",
          "aries_scorpio_business":
              "Qadın-Qoç və Kişi-Əqrəb\nBu, iki enerjili şəxsin yorulmaz bir birliyidir. Nə iş görsələr, layihə 'yanacaq'. Yorulmaz həvəskarlar olan qadın-Qoç və kişi-Əqrəb hər hansı bir layihəyə lazım olan impulsu verə bilərlər — amma detalların işlənməsi onlara çətinliklə gələcək. Kişi-Əqrəb daha diqqətli və detallı yanaşma tələb edən sahələrdə uğurlu ola bilər, qadın-Qoç isə bu prosesi əsəbiləşdirə bilər.\nAmma əgər məqsəd həqiqətən dəyərlidirsə, qadın-Qoç özünü təşkil edə bilər və lazımi nəticəni əldə edə bilər.\n\nQadın-Əqrəb və Kişi-Qoç\nBu, iki enerjili şəxsin birliyidir ki, məqsədlərinə çatmağı çox sevirlər. Daha dəqiq desək, onlara daha çox bir şeyi 'ələ keçirmək' prosesi maraqlıdır. Onların fəaliyyət göstərdiyi peşə sahəsinə görə, rolları belə olacaq: qadın daha detalçı yanaşma tələb edən, intelektual əmək tələb edən sahələrdə uğurlu olacaq, kişi-Qoç isə düşünmədən hərəkət etməyə ehtiyac olan yerlərdə uğur qazanacaq.",
          "aries_sagittarius_message":
              "Uyğunluq: 92%. Qadında, əlbəttə ki, daha çox atəş var, amma kişi də öz yerini bilir. Lakin bu parlaq qadın sahibkarlıq meylləri olan kişiyə qarşı onun azadlıqsevərliyini qəbul edə biləcəkmi?",
          "aries_sagittarius_love":
              "Qadın-Qoç və Kişi-Oxatan\nOnların münasibətləri çox ehtiraslı olacaq, çünki həm qadın-Qoç, həm də kişi-Oxatan Atəş ünsürünə aid olurlar. Fərq ondadır ki, qadın-Qoç ilkin atəşdir, parlaq bir qığılcımdır, ən isti, ən güclüdür. Kişi-Oxatan isə daha sabit, istilik saçan, lakin yandırmayan bir alovdur. Ola bilsin ki, qadın-Qoçun enerjisi onun üçün həddən artıq olacaq — kişi-Oxatan hərarətli olsa da, daha sadə və asan münasibətlərin tərəfdarıdır. Qadın-Qoç isə tərəfdaşından tam öhdəlik, tam birləşmə tələb edir. O, sevgiyə tamamilə qərq olur və sevdiyi şəxsin də bu cür davranmasını gözləyir. Lakin kişi-Oxatan bir qadına bağlı qalmağa tələsmir, hətta bu qadın Qoç olsa belə. Bu vəziyyət, təbii ki, qadın-Qoçu qane etmir, o, inciyir və özünü kifayət qədər sevilməyən və lazım olmayan hiss edir. Kişi-Oxatana münasibətlərdə hava lazımdır, qadın-Qoç isə sevgisi ilə onu boğur. Lakin o bir az sərbəstlik versə, kişi-Oxatan da azadlığını bir qədər məhdudlaşdırsaydı, onlar çox güclü və uzunmüddətli münasibətlər qura bilərlər.\n\nQadın-Oxatan və Kişi-Qoç\nQadın-Oxatan və kişi-Qoç bir-birini dərhal fərq edəcəklər. Onların tükənməz nikbinliyi, enerjisi və xarici görünüşlərində xüsusi bir ehtiras var. Qadın-Oxatanı nə qədər gözəl olursa olsun, kişi-Qoç onun təbəssümünün arxasında nəyin gizləndiyini öyrənmək istəyəcək, qadın isə onda bir fəthçi olduğunu hiss edəcək. Onların sevgisi incə və sakit olmayacaq — kişi-Qoç ilə sakitlikdən ümumiyyətlə söhbət belə gedə bilməz. Kişi onu tamamilə fəth edə bilməyəcək, çünki qadın-Oxatan azadlığı sevir və kişiyə təslim olmaq niyyətində deyil. Kişi-Qoç, niyə onun təzyiqinə müqavimət göstərdiyini anlamayacaq, çünki onlar çox bənzəyirlər. Qadın-Oxatan intuitiv olaraq başa düşür ki, kişi-Qoç onun özünə uyğunlaşmasını istəyir, lakin qadın bunu edə bilməz, bütün varlığı onun müstəqilliyini qoruyur. Bu münasibətləri bir mübarizə kimi adlandırmaq olar, amma burada məğlub olanlar olmayacaq. Onlar hər ikisi qalib gələcəklər, çünki bir-birinə layiqdirlər. Qadın-Oxatan və kişi-Qoç uzunmüddətli və güclü sevgi münasibətləri qura bilərlər, amma onlarda həmişə nəyinsə çatışmadığını hiss edəcəklər.",
          "aries_sagittarius_family":
              "Qadın-Qoç və Kişi-Oxatan\nQadın-Qoç və kişi-Oxatan arasında nikah uğurlu olacaq, çünki hər ikisi aktiv, enerjili və oxşar dəyərlərə malikdirlər. Həm qadın-Qoç, həm də kişi-Oxatan adi, sakit bir həyat arzulamayacaqlar — hər ikisi fəthləri və macəraları sevirlər. Bəlkə də, 'Ana, ata, mən — idman ailəsiyik' yarışmasında birinci yeri tutacaqlar, səhərlər birlikdə qaçışlar edəcək, meşədə göbələk toplayacaq və xizəklə sürüşəcəklər. Onların övladları bu cür valideynlərlə heç vaxt darıxmayacaq.\n\nQadın-Oxatan və Kişi-Qoç\nNikahda qadın-Oxatan və kişi-Qoç özlərini çox yaxşı hiss edəcəklər, onların dəyərləri və dünyagörüşləri çox oxşardır, buna görə də ailə həyatına baxışları da bir çox cəhətdən üst-üstə düşəcək. Qadın-Oxatan mükəmməl bir həyat yoldaşı və ev sahibi olmağı bacaracaq, o, çox yüksək aktivliyi ilə seçilir. Lakin o, yalnız həyat yoldaşı rolu ilə kifayətlənməməlidir, çünki onun ictimai həyat sürmək arzusu kifayət qədər böyükdür və əgər bu istəyini boğmağa çalışsa, əri üçün asan olmayacaq. O, hirslənəcək və bunu ərindən çıxacaq — ona görə də qadın başqa bir fəaliyyətlə məşğul olsa, ev ocağını qorumaqdan əlavə, bu, daha yaxşı olar. Kişi-Qoç əla bir həyat yoldaşı ola bilər — amma o, səbir və anlayışa yiyələnməli olacaq, çünki ailə həyatı məhz bu keyfiyyətlər üzərində qurulur. Əslində, bu keyfiyyətlər onlarda çox da inkişaf etməyib.",
          "aries_sagittarius_friendship":
              "Qadın-Qoç və Kişi-Oxatan\nQadın-Qoç və kişi-Oxatanın danışacaq çox mövzusu olacaq: onların hər ikisi aktiv həyat tərzini sevir və bir yerdə uzun müddət otura bilmirlər. Onlar bir-birini hər bir başlanğıcda dəstəkləyəcəklər. Lakin qadın-Qoçun kişi-Oxatanın məntiqsizliyi həmişə başa düşülən olmayacaq — qadın-Qoç nəyi və hansı ardıcıllıqla etməli olduğunu bilməkdən xoşlanır. Kişi-Oxatan qadının həyatına zaman-zaman daxil olacaq, lakin hətta bu qeyri-müntəzəmliyi belə onların dostluğunu pozmağa səbəb olmayacaq.\n\nQadın-Oxatan və Kişi-Qoç\nOd ünsürünün nümayəndələri arasında dostluq həmişə çox parlaq və uzunmüddətli olur. Onlar münasibətlərinə bütün ruhları ilə bağlıdırlar və qadın-Oxatan və kişi-Qoç da bu istisna deyil. Birlikdə bu iki insan dağları yerindən oynada bilər: kişi-Qoçun enerjisini götürün və ona qadın-Oxatanın cəsarətini əlavə edin — indi anlayırsınız ki, bu, necə dostlardır? Onlar idmanla məşğul ola bilərlər, yürüşlərə çıxa bilərlər, teatr və kinoya gedə bilərlər, yüksək və sakit musiqi dinləyə bilərlər. Bir sözlə, onlar mütləq bir-birinə uyğun gələcəklər. Və çox güman ki, uzun müddət.",
          "aries_sagittarius_business":
              "Qadın-Qoç və Kişi-Oxatan\nƏgər onlar birlikdə işləmək üçün birləşsələr, böyük nəticələr əldə edəcəklər. Əlbəttə ki, prosesin tam və fasiləsiz olması üçün onlara başqa ünsürlərin və bürclərin nümayəndələri (əsasən yer ünsürü) lazım olacaq, lakin qadın-Qoç və kişi-Oxatan birlikdə hər hansı bir layihənin yaxşı başlanğıcı üçün zəruri olan ilkin impulsu meydana gətirirlər. Məsələ yaradıcılıq və ya elm, xidmət sahəsi və ya istehsalatla bağlı olub-olmamasından asılı olmayaraq — bu iki insan bir qığılcım yaradacaqlar və bu, sabit bir alova çevriləcək.\n\nQadın-Oxatan və Kişi-Qoç\nQadın-Oxatan və kişi-Qoç birgə iş aparmaq üçün çox uyğun bir cütdür. Hər ikisi risk etməyi sevir və bacarır, pul qazanmağı və ətrafdakı insanlara təsir göstərməyi, özlərini göstərməyi sevirlər. Onlar mütləq işləyəcəklər, çünki onların metodları oxşardır və məqsədləri üst-üstə düşür. Onlar yaradıcılıqda da böyük uğurlar qazana bilərlər, çünki onlara məxsus olan Od ünsürü nümayəndələrini xüsusi bir yaradıcılıq istedadı ilə təmin edir.",
          "aries_capricorn_message":
              "Uyğunluq 82%. Qadın öz tərsliyi ilə heyran edir, kişi isə inadkarlığı ilə. Belə oxşar sözlər, amma tamamilə fərqli məna.",
          "aries_capricorn_love":
              "Qadın-Qoç və Kişi-Oğlaq\nQadın-Qoç hətta ilk baxışda ümidsiz görünən bir insan olan Kişi-Oğlaqda sevgi hissini oyada bilər. Təbii ki, onun birbaşa danışığı Kişi-Oğlağa xoş gəlməyə bilər, amma məqsədinə çatacaq: Kişi-Oğlaq aşiq olacaq. O, ona Kişi-Oğlaqın içində hansı gücdə və intensivlikdə bir atəşin yandığını göstərə biləcək — bu, sevgi və ehtiras atəşidir. Yəqin ki, başqa heç kim Kişi-Oğlağa bu cür təbiətini göstərə bilməzdi, bu xarakter yalnız başqalarından deyil, bəzən onun özündən də gizlənir. O isə ona həmişə axtardığı etibarı verəcək. Qadın-Qoç hər zaman daimi bir sevgiyə, tərəfdaşdan sədaqət və emosional sabitlik gözləyir. Kişi-Oğlaq məhz belə biridir. Onların sevgisi minlərlə maneəni aşa biləcək və bu, onları daha da güclü edəcək. Yeganə problem ondan ibarətdir ki, hər ikisində zəriflik və yumşaqlıq çatışmazlığı ola bilər. Bununla belə, onlar sentimental çatışmazlıq hiss etməyə də bilərlər.\n\nQadın-Oğlaq və Kişi-Qoç\nQadın-Oğlaq — əsl Qar Kraliçasıdır, amma içində isti bir ürək var. Necə ərimədiyi məlum deyil, amma onu tamamilə əridə biləcək tək insan Kişi-Qoçdur. O, elə bir temperamentə malikdir ki, bu qadının daxili özünütəsəvvürü ilə uyğunlaşır. Kişi-Qoç isti, odlu — əsl kişidir. Qadın-Oğlaq onun diqqətindən məmnun qalacaq. O, hər ikisi arasında ortaq bir şey hiss edəcək, baxmayaraq ki, zahirən tamamilə fərqli görünürlər. O, onda əsl qadını oyada biləcək, baxmayaraq ki, qalibiyyətə aparan yolda bir çox rədd cavabını alacaq. Qadın-Oğlaq öz xarakterini bir qədər yumşaltmalıdır ki, Kişi-Qoçu onun soyuqluğu ilə incitməsin.",
          "aries_capricorn_family":
              "Qadın-Qoç və Kişi-Oğlaq\nKişi-Oğlaq ailəyə çox ciddi yanaşan biridir. O, heç vaxt tələsik, ilk baxışda sevgiyə əsaslanaraq evlənməz. Ona öz tərəfdaşını tam tanımaq, onu başdan-ayağa öyrənmək lazımdır. Qadın-Qoç isə tez-tez münasibətləri rəsmiləşdirmək istəyir, çünki sevdiyi şəxsi “sahib çıxmaq”, onun həyatının bir hissəsi olmaq, onun ailəsinə çevrilmək istəyir. Bu baxımdan baxışlar və istəklər üst-üstə düşmədikdə, Qadın-Qoç və Kişi-Oğlaq arasında anlaşılmazlıq yarana bilər: o, ondan evlilik təklifini tələb edəcək, amma kişi-Oğlaq daha da müqavimət göstərəcək. Lakin onların münasibətləri zamanın sınağından keçibsə və Kişi-Oğlaq tərs sevgilisinə evlənmək üçün tələsirsə, bu, ideal ailə həyatı üçün ən yaxşı variant olacaq.\n\nQadın-Oğlaq və Kişi-Qoç\nQadın-Oğlaq həqiqətən evlənmək istəyir (baxmayaraq ki, əksini iddia edir), Kişi-Qoç da tez-tez evlənmək istəyir. Amma onların arzularının səbəbləri fərqlidir: Qadın-Oğlaq nəhayət münasibətlərə başqa bir status vermək, özünü sosial cəhətdən qorumaq, həyatında yeni bir dövr başlatmaq istəyir. Kişi-Qoç isə sadəcə istəyir ki, bu qadın yalnız onun olsun. Kişi-Qoç elə bilir ki, evliliklə Qadın-Oğlaqı özünə bağlayacaq — amma belə deyil. Onların ailə həyatı, evlilikdən əvvəlki münasibətlərdən heç də sakit olmayacaq, amma bəlkə də illər keçdikcə bu iki insan daha sakit olacaq. Amma heç bir zəmanət yoxdur.",
          "aries_capricorn_friendship":
              "Qadın-Qoç və Kişi-Oğlaq\nOnlar dost ola bilərlər: Qadın-Qoç Kişi-Oğlağa onun emosional problemləri ilə mübarizə aparmağa kömək edəcək (biz hamımız bilirik ki, Oğlaqların tez-tez depressiya halları olur). Kişi-Oğlaq isə ona mənəviyyat və əxlaqın çərçivəsindən kənara çıxan məsələləri həll etməyə kömək edəcək, sadəcə ağıllı və məntiqli bir qərar qəbul etmək lazım olanda. Onlar bir-birinə lazımdırlar, çünki bir-birlərini tamamlayan və digərinə çatışmayan xarakter keyfiyyətlərinə malikdirlər. Hər ikisi uzunmüddətli münasibətlərə yönəldikləri üçün onların dostluğu uzun və xoş olacaq.\n\nQadın-Oğlaq və Kişi-Qoç\nOnlar dost ola bilərlər, amma mütləq birlikdə enerji sərf edəcək bir fəaliyyətlə məşğul olmalıdırlar. Bu, məsələn, birgə gəzintilər və ya idman məşğələləri ola bilər. Əsas odur ki, onlara darıxdırıcı və qəmgin olmasın: emosional və fiziki zənginlik onların birgə əyləncə vaxtının əsas şərtidir və bu, uzun və möhkəm dostluq münasibətlərinin qurulması üçün vacibdir.",
          "aries_capricorn_business":
              "Qadın-Qoç və Kişi-Oğlaq\nQadın-Qoç və Kişi-Oğlaqın iş birliyində qadın hər hansı bir yeniliyin təşəbbüskarı rolunu oynayacaq, kişi isə istədikləri nəticəyə nail olmaq üçün hərəkət etmə sxemini quracaq. Qadın-Qoç ideyalarla dolu olacaq, onu — bir az yavaş, ciddi və tutqun olan Oğlaq kişisini coşduracaq. O isə qadının fantaziyalarına həddindən artıq qapıldıqda onun həddindən artıq ehtirasını soyutmağı bacaracaq.\n\nQadın-Oğlaq və Kişi-Qoç\nOnlar işləməyi bacarırlar, amma bir az fərqli şəkildə. Qadın-Oğlaq plan qurur və sonra onu addım-addım həyata keçirir, Kişi-Qoç isə planlaşdırmağa alışmayıb. Amma dəli enerjisi sayəsində öz hədəfinə çatır və nəticə əldə edir. Onların müstəqil işləmələri daha yaxşı olar, əks halda fikir ayrılıqları qaçılmazdır. Mübahisələrə səbəb ola biləcək başqa bir məqam risk etməyə olan həvəsdir — Kişi-Qoçun riski artırma arzusu və Qadın-Oğlaqın riskləri azaltma istəyi. Bu məsələdə razılığa gəlmək onlar üçün həqiqətən çətin olacaq. Ancaq çıxış yolu var: yenə də müstəqil fəaliyyət göstərmək, mübahisəli məqamları müzakirə etməmək və məsuliyyəti (və ya hərəkətsizliyi) tamamilə öz üzərinə götürmək.",
          "aries_aquarius_message":
              "Uyğunluq 82%. Qadın parlaq və tələskən, kişi isə gözlənilməz və azadlığı sevəndir. Qadın onu saxlaya biləcəkmi? Kişi ona layiqli müqavimət göstərə biləcəkmi, amma ifrata varmadan?",
          "aries_aquarius_love":
              "Qadın-Qoç və Kişi-Dolça\nBu ikisi uzun müddət bir-birlərini anlamayacaqlar. Qadın-Qoç ehtiras axtardığı yerdə, Kişi-Dolça dostluq axtarır. O, artıq daha böyük bir şeyə keçməyə hazır olanda, kişi-Dolça qəfildən gedə bilər və onu tam çaşqınlıq içində qoyar. Kişi-Dolça tamamilə mülkiyyətçilik hissindən məhrumdur, qadın-Qoç isə onun təcəssümüdür. Onların münasibətləri pişik-siçan oyununa bənzəyəcək, və pişik, təbii ki, o olacaq. Qadın-Qoç Kişi-Dolçanın onun qaydalarına riayət etmək istəməməsindən narahat olacaq: o, ümumiyyətlə, heç bir məhdudiyyətə qarşı deyil, xüsusən də bunları özü uydurmayıb. Münasibətlərinin inkişaf yolları iki yoldur: ya qadın ona çatmaqdan və sevgilərini ümumi məxrəcə gətirmək cəhdlərindən yorulacaq və tez ayrılacaqlar, ya da kişi ona bir üstünlük verib itaətkarlıq illüziyasını yaradacaq — o zaman uzunmüddətli münasibətlərin şansı olduqca böyükdür.\n\nQadın-Dolça və Kişi-Qoç\nOnlar bir-birlərini özlərində çatışmayan şeylərlə cəlb edəcəklər. Onu mütləq onun qətiyyəti maraqlandıracaq. O, baxmayaraq ki, kimlə ünsiyyət quracağını və kimdən uzaq duracağını özü həll etməyə öyrəşib, onun israrını mütləq qeyd edəcək. Qadın-Dolçaya onun təslim olmaması, onun qəlbini fəth etmək cəhdləri xoş gələcək. Kişi-Qoç isə onun nümayiş etdirdiyi soyuqqanlılıqdan və ona təslim olmağa tələsməməsindən heyran olacaq. O, Od ünsürünə, o isə Hava ünsürünə aiddir. O, onu həm qızışdıra, həm də demək olar ki, söndürə bilər — lakin onun təbii yaxşılığı onun alovunu məhv etməyə imkan vermir. Qadın-Dolça və Kişi-Qoç arasındakı münasibətlərin böyük üstünlüyü odur ki, bu romantika əbədi ola bilər, çünki o, qazanmağı sevir və ona nail olmaq demək olar ki, mümkün deyil. Beləliklə, o, onun pəncərələrinin altında serenadalar oxuyacaq, o isə ona çox lazım olduğunu hiss edərək əriməyə başlayacaq.",
          "aries_aquarius_family":
              "Qadın-Qoç və Kişi-Dolça\nƏgər onlar evlənsələr, ailədə əsas olan qadın olacaq. Kişi-Dolça isə tabe olan biri deyil — sadəcə, əsl hakimiyyət hər halda qadın-Qoça məxsusdur. Kişi-Dolça hər hansı bir məsələyə minlərlə ağıllı və orijinal həll təklif edəcək, amma qadın həmin məsələdə hansı həlli qəbul edəcəklərinə qərar verəcək. Onların ailəsi mütləq matriarxatın nümunəsi olmaya bilər — ola bilsin ki, ətrafdakılar belə, bu ailədə kimə tabe olduğunu belə görməyəcəklər. Qadın-Qoç və Kişi-Dolça evliliyi olduqca ahəngdar bir haldır. Onlar bir-birinə yanaşmağı bacaracaq və ailəni uzun illər qoruyub saxlayacaqlar.\n\nQadın-Dolça və Kişi-Qoç\nKişi onun diqqətini qazanmaq üçün nə qədər səy göstərdiyini nəzərə alaraq, qadın-Dolça ilə Kişi-Qoç arasında evlilik mümkündür. O, qadını tamamilə özününkü etmək üçün daha çox səy göstərəcək. Problem odur ki, qadın-Dolça rəsmi prosedurlardan nifrət edir və ümumiyyətlə kiməsə aid olmaq istəmir. O, adətən, tipik qadın ev sahibəsi rolunu cazibədar hesab etmir, ona görə də kişi-Qoç, ona öz soyadını versə belə, qayğıkeş bir həyat yoldaşı əldə edəcəyini gözləməməlidir.",
          "aries_aquarius_friendship":
              "Qadın-Qoç və Kişi-Dolça\nQadın-Qoç və Kişi-Dolça arasında dostluq tamamilə mümkündür. O, ona əsasən emosional dəstək və qoruma verəcək, kişi isə ona hər şeyin tamamilə dağıldığını düşündüyü zaman gedə biləcəyi yüzlərlə yolu təklif edəcək. Birlikdə onlar axşamlar toplaşaraq dərindən söhbət etməyə, bir-birindən heç nə tələb etməyib, eyni zamanda bir-birlərinə çox şey verməyə imkan verən bir klub təşkil edə bilərlər.\n\nQadın-Dolça və Kişi-Qoç\nQadın-Dolça dostluğun nə olduğunu yaxşı başa düşür, ona görə də onların dostluq münasibətlərində aparıcı məhz o olacaq. Onun necə vaxt keçirmək ideyaları kişi tərəfindən böyük həvəslə qəbul ediləcək. Qadın-Dolça həvəsli təbiətlidir, ona görə də onun dostu həmişə onunla maraqlı olacaq. O, Kişi-Qoçu öz ruhani istiliyi ilə isidəcək, o isə yanında olaraq güc toplayacaq. Əgər ona möhkəm kişi dost çiyni lazım olarsa, o, həmişə bu çiyni təklif edəcək — buna heç şübhə yoxdur.",
          "aries_aquarius_business":
              "Qadın-Qoç və Kişi-Dolça\nÇox güman ki, kişi-Dolça nəsə yeni bir şey icad edəcək və qadın-Qoç parlaq ideyanı eşidib onu həyata keçirməkdən özünü saxlaya bilməyəcək. Beləliklə, onların işlərində belə bir ardıcıllıq yaranacaq: Kişi-Dolça layihənin 'daxili məzmununu' idarə edəcək, qadın-Qoç isə həmin məzmuna aşiq olaraq layihəyə lazım olan insanları və resursları cəlb edəcək. Onların hər ikisi Yer ünsüründən məhrumdur — bu, ideyaların həyata keçirilməsindən cavabdeh olan ünsürdür, ona görə də onların işini başqaları, daha 'maddi' insanlar götürməlidir.\n\nQadın-Dolça və Kişi-Qoç\nƏgər onlar birlikdə işləməli olsalar, bir-birindən çox şey öyrənə bilərlər. Məsələn, Kişi-Qoç daha düşüncəli olacaq, hərəkətlərini təhlil etməyə daha çox vaxt ayıracaq — bunu ona qadın-Dolça öyrədəcək. Qadın isə belə canlı və təşəbbüskar bir tərəfdaşla birlikdə işləyərkən daha cəsarətli və təşəbbüskar olacaq. Onlar öz bizneslərini təşkil edə bilərlər, çünki ikisinin də ideyaları və enerjisi kifayət qədərdir.",
          "aries_pisces_message":
              "Uyğunluq faizi: 87%. Onlar çox fərqlidirlər. Qadın parlaq və enerjilidir, kişi isə sakit və passivdir. Bəlkə də qadın, öz enerjisi ilə kişini hərəkətə gətirə bilər.",
          "aries_pisces_love":
              "Qadın-Qoç və Kişi-Balıqlar\nQadın-Qoç üçün rahatlamaq çox çətindir. Kişi-Balıqlar isə rahatlamağın ustasıdır. Onların münasibətlərini birgə meditasiya kimi təsvir etmək olar. Amma rahatlamaqdan sonra gərginlik gəlir və bu zaman qadın hərəkətə keçir. Onlar aktivlik və passivliyi növbələşdirməyi bacarırlar - hər ikisi bu ritmdən zövq alır. Kişi-Balıqlar, qadın-Qoçun sakitləşməsi və sadəcə susması lazım olan anı incəliklə hiss edir. Qadın-Qoç isə öz növbəsində, kişinin onun enerjisinə ehtiyac duyduğunu hiss edir və onu bu enerji ilə təmin edir. Onların sevgi münasibətləri 'mənim böyük sevgim ikimizə də kifayətdir' ifadəsinə uyğundur. Qadın-Qoçun sevgisi canlı, dinamik və fəth edəndir (kişinin də bu xoşuna gəlir). Kişi-Balıqların sevgisi isə müşahidəçi, yumşaq və mərhəmətlidir. Onlar bir-birilərinin tam hissəsi olmasalar da, bir-birilərini tamamlayan vacib parçalar olduqlarını hiss edir və bu münasibətləri qoruyurlar.\n\nQadın-Balıqlar və Kişi-Qoç\nQadın-Balıqlar və Kişi-Qoç arasındakı münasibətlər zəngin, ehtiraslı və maraqlı olur. Bu, temperamentlərin bir-birini tamamlaması ilə uyğun gələn bir nümunədir. Kişi aktivdir, qadın isə passiv. Kişi cəsurdur, qadın isə çox qorxuları var. Kişi fəth etməyi sevir, qadın isə fəth olunmağı gözləyir. Ümumilikdə, bu, çox harmonik bir cütdür, burada qadın həqiqətən qadın keyfiyyətlərinə, kişi isə kişi keyfiyyətlərinə malikdir. Problemlər, kişinin həddindən artıq aqressivliyindən və qadının həddindən artıq passivliyindən qaynaqlana bilər. Qadın-Balıqlar münasibətlərin çox sakit və cansıxıcı olmasına səbəb ola bilər. Münaqişələr də onların sevgisinin vacib bir hissəsidir. Kişi-Qoç və Qadın-Balıqların münasibətləri bir növ mübarizə oyunu kimidir - onlar mübahisə edib barışmağı sevirlər və bu, onları daha da yaxınlaşdırır.",
          "aries_pisces_family":
              "Qadın-Qoç və Kişi-Balıqlar\nQadın-Qoç və Kişi-Balıqlar arasında evlilik yaxşı bir ideyadır. Çünki onların hər ikisində bir-birini tamamlayan xüsusiyyətlər var. Qadın-Qoç ailənin dirəyi kimi çıxış edir, Kişi-Balıqlar isə ailə atmosferini yaradaraq, ailə həyatının istiqamətini müəyyənləşdirir. Onların övladları bu cür evlilikdə həm fiziki rahatlıq (qadının məsuliyyətində), həm də ruhani rahatlıq (kişinin rəhbərliyi altında) içində böyüyürlər. Tez-tez Kişi-Balıqlar qadında öz atasını xatırladan bir obraz yaradır və bu paralellər münasibətlərdə bir çox məsələləri həll etməyə kömək edir.\n\nQadın-Balıqlar və Kişi-Qoç\nOnların evliliyi ideal ola bilər. Qadın-Balıqlar çox evdar olmasa da - gününü düşüncələrlə keçirə bilər, amma o, sevgi dolu həyat yoldaşı və ana olacaq. Kişi-Qoç isə ailənin təminatçısı və qoruyucusudur. Doğrudur, kişinin aqressiyası bəzən onu qabaqlayır, amma qadın-Balıqlar bunu öhdəsindən gələ bilər, lazım olanda ona sevgi ilə yanaşaraq. Onların evliliyi uzun müddət davam edə bilər, xüsusən də Kişi-Qoç öz qadınını asanlıqla buraxmayacaq. Qadın-Balıqlar isə həmişə sevilmək və qorunmaq arzusundadır.",
          "aries_pisces_friendship":
              "Qadın-Qoç və Kişi-Balıqlar\nQadın-Qoç və Kişi-Balıqlar arasında dostluq çox isti və mehriban ola bilər. Onlar bir-birinə ruhən və maddi olaraq dəstək olurlar. Təbii ki, Kişi-Balıqları ən etibarlı dost adlandırmaq olmaz, çünki o, vəziyyət gərginləşəndə və ondan konkret yardım gözləniləndə yox ola bilər. Amma qadın-Qoç inadkarlığı ilə onu sonadək dostluğunu davam etdirməyə və etibarlı bir dost olmağa məcbur edə bilər.\n\nQadın-Balıqlar və Kişi-Qoç\nOnlar dostluq edə bilərlər, amma bu dostluq hər zaman bir qədər həssaslıq və romantika ilə dolu olacaq - bəs niyə onlar görüşmürlər? Onlar uzun-uzadı söhbətlər edir, kitablar, filmlər müzakirə edir, yaxınlıqdakı bir bara birlikdə gedib rahatlanırlar və bu, onları digər insanlar arasındakı istənilən çətinliklərdən daha çox birləşdirir. Onlara bir-birini daha yaxşı tanımaq üçün çox vaxt lazım deyil; sadəcə bir dəfə danışmaq yetərlidir, və hər ikisi başa düşəcək ki, daha yaxşı bir dost tapa bilməzlər.",
          "aries_pisces_business":
              "Qadın-Qoç və Kişi-Balıqlar\nBirlikdə onlar böyük uğurlara nail ola bilərlər. Qadın-Qoç iş birliyinə enerji verir, Kişi-Balıqlar isə prosesi ustalıqla idarə edir. Kişi-Balıqlar lazımi ideyanı lazımi vaxtda təqdim etməyi bacarır, qadın isə komandanı toplayır və istənilən nəticəni əldə etmək üçün işləri təşkil edir. Detallarla əlaqəli işlərdə Kişi-Balıqlara etibar etmək olmaz - burada qadın-Qoç və Kişi-Balıqların birgə işləməsi üçün daha maddi işlərə diqqət yetirmək üçün başqa birini tapmaq lazımdır. Bunun xaricində, bu, çox uğurlu bir iş birliyidir.\n\nQadın-Balıqlar və Kişi-Qoç\nBirlikdə işləmək onların məhsuldarlığına çox müsbət təsir göstərir: Kişi-Qoç, həmişə hərəkətdə və canlı olan, Qadın-Balıqları enerji ilə doldurur, o isə tez-tez öz qərarsızlığından əziyyət çəkir. Qadın isə onu rahatlaşdırır, ona yaxşı əhval-ruhiyyə bəxş edir ki, daha yaxşı işləyə bilsin. Onlar hər hansı bir sahədə birlikdə işləyə bilərlər: bu yaradıcı sahə, xidmətlər, istehsalat və ya ticarət ola bilər. Qadın-Balıqlar Kişi-Qoç ilə digər insanlar arasında əlaqəni təmin edir və onun iş münasibətlərini tənzimləyərək uğur qazanmasına kömək edir.",
          "taurus_gemini_message":
              "Uyğunluq: 73%. O, ayaqları yerə möhkəm basan, praktiki düşüncəli bir qadındır, kişi isə yüngül və dəymədüşərdir. Bu qadının yanında uzun müddət qala biləcəkmi?",
          "taurus_gemini_love":
              "Qadın-Buğa və Kişi-Əkizlər\nKişi-Əkizlər qadın-Buğanın qəlbini asanlıqla fəth edə bilər. Əvvəla, o, daim qadının gözləri önündədir, ona diqqət göstərir – qadın-Buğalar, hər nə qədər etiraf etməsələr də, diqqəti çox sevirlər və hətta ondan bir az da çoxunu istəyərlər (çox vaxt isə bezdirici sadiq qalanlardan şikayət edirlər). O, qadına təzə zarafatlar təqdim edər, qadın isə ona daha ciddi bir şey təqdim edər.\nBu cütlük kifayət qədər ahəngdar olacaq: o, qadının yanında darıxmayacaq, qadın isə kişinin sevgisini və qayğısını hiss edəcək – qadın-Buğanın verdiyi hisslər çox hissedilən və realdır.\n\nQadın-Əkizlər və Kişi-Buğa\nQadın-Əkizlər və kişi-Buğa arasındakı münasibətlər sadəliyi və müəyyən qədər soyuqluğu ilə seçilir, hərçənd ki, onlar bir-birinə yaxşı uyğun gəlir. Qadın-Əkizlər bu yerli kişidən coşqun sevgi etirafları gözləyəcək – çünki bu çox xoşdur! – kişi isə sözlərini qənaətlə, az miqdarda sərf edəcək. Onlar birlikdə maraqlı vaxt keçirə bilərlər, ta ki, qadın-Əkizlərin ilham mənbəyi tükənənə qədər. Bu baş verəndə, o, dərhal kənarda yeni enerji toplamaq üçün kiminləsə ünsiyyət qurmalı olacaq – özü kimi sosial yönümlü biri ilə. Bu vaxt kişi-Buğa isə təkbaşına qalıb, özünə qapanaraq gücünü bərpa edəcək. Əgər onlar ünsiyyət və bir-birindən istirahət dövrlərini ustalıqla dəyişsələr, onların münasibətləri temperament fərqlərinə baxmayaraq, çox uzun müddət davam edə bilər.",
          "taurus_gemini_family":
              "Qadın-Buğa və Kişi-Əkizlər\nÇox güman ki, evlilik təklifini edən qadın-Buğa olacaq. Hərçənd ki, məsuliyyətli kişi-Əkizlər də mövcuddur, amma onlar istisnadırlar, qaydanı təsdiq edən istisna. Əslində isə evlilik və ailəyə daha çox qadın-Buğa ehtiyac duyur. Əkizlər bürcü təbiəti uzunmüddətli və möhkəm əlaqələri nəzərdə tutmur: Əkizlər bürcü dəyişkənliyin simvoludur. Amma məhz qadın-Buğa bu narahat tədqiqatçını sakitləşdirə bilər. Əgər onların uşaqları olarsa, qadın-Buğa onları fiziki cəhətdən böyütməyi sevinclə yerinə yetirəcək, kişi-Əkizlər isə onları öyrədib əyləndirəcək – vaxtilə o, qadının diqqətini qazanmaq üçün onu necə əyləndirirdisə, uşaqları da elə əyləndirəcək.\n\nQadın-Əkizlər və Kişi-Buğa\nOnların evliliyi çox möhkəm ola bilər. Qadın-Əkizlər hər hansı bir xarakterə uyğunlaşma qabiliyyətinə malikdir və kişi-Buğanın xarakteri isə, necə deyərlər, qızıl kimidir. Ailədə rollar ənənəvi şəkildə bölüşdürüləcək, amma əgər kişi-Buğa ideal ər obrazına uyğun gəlsə, öz ailəsini təmin edib qoruyarsa, qadın-Əkizlərə yaxşı evdar qadın olmaq çətin olacaq. O, daim hərəkətdə olmağa və öz maraqlarına uyğun işlərlə məşğul olmağa öyrəşib – ev işi isə onun üçün çox darıxdırıcıdır. Amma kişi-Buğa da öz qayğısına qala bilər (əgər onların münasibətləri onu tamamilə qane edərsə).",
          "taurus_gemini_friendship":
              "Qadın-Buğa və Kişi-Əkizlər\nBu, təsadüfi olaraq baş verən dostluq ola bilər. Əgər onlar bir-birinə aşiq deyillərsə, birlikdə əylənmək olar. Kişi-Əkizlər nadir dostluqsevərliyi və aqressivliyin olmaması ilə seçilir, buna görə də o, qızların sevimli dostudur. Onunla ünsiyyət rahat və xoşdur. Qadın-Buğa isə dostluğu daha yavaş qurur, xüsusilə kişilərlə, amma bu kişi ona xoş gələcək. Kişi-Əkizlərin yanında qadın-Buğa özü ola bilər, istədiyi mövzuda söhbət edə bilər və bol-bol gülə bilər. Bəlkə də, zaman keçdikcə bu dostluq romançılığa çevrilə bilər, kim bilir?\n\nQadın-Əkizlər və Kişi-Buğa\nQadın-Əkizlər və kişi-Buğa arasındakı dostluq çox möhkəm ola bilər, onları ünsiyyət sevgisi və maraqlı vaxt keçirilməsi birləşdirir. Qadın-Əkizlər kişi-Buğanı hər zaman dəstəkləyəcək, ona ruh yüksəkliyi bəxş edəcək. O isə qadını real dünyanın çətinlikləri ilə üzləşəndə təsəlli edəcək. Onlar bir-birinə çox narahatlıq yaratmazlar – amma qadın-Əkizlər bəzən anlamayacaq ki, niyə onun dostu onların ünsiyyətinə o qədər də ehtiyac duymur.",
          "taurus_gemini_business":
              "Qadın-Buğa və Kişi-Əkizlər\nHava ünsürü nümayəndələri kimi, kişi-Əkizlər daim ideyalarla doludur, amma onları həyata keçirmək ona bəzən çətin olur. Qadın-Buğa bu ideyaların nə dərəcədə perspektivli və həyata keçirilə bilən olduğunu başa düşəcək. O, hər şeyi hesablayacaq, planlayacaq və nəticəyə çatmaq üçün lazım olan hərəkətləri müəyyənləşdirəcək. Əlbəttə ki, ona tənbəllik etməsə. Buğa bürcü müəyyən qədər qaçma meyli ilə xarakterizə olunur və qadınlar bu məsələdə kişilərdən daha çox əziyyət çəkir. Buna görə də, əgər kişi-Əkizlər və qadın-Buğa birgə iş görürlərsə, kişiyə qadını daim ruhlandırmaq və motivasiya etmək lazım gələcək – əks halda heç nə işləməyəcək. Bu tərəfdaşlıqda qadın-Buğa bir növ mühərrik rolunu oynayır – o işə salındıqdan sonra, sakitcə davam etmək olar, yanacaqın ən uyğun olmayan anda bitməsindən qorxmadan.\n\nQadın-Əkizlər və Kişi-Buğa\nQadın-Əkizlər və kişi-Buğa birlikdə demək olar ki, istənilən işi uğurla yerinə yetirə bilərlər. Qadın-Əkizlər ideya ilhamçısı rolunu oynayacaq, kişi-Buğa isə proseslərin texnologiyasını izləyəcək, nəzərdə tutulanı həyata keçirmək üçün üsullar düşünəcək. Onların daxili ritmləri tez-tez uyğun gəlmir: qadın-Əkizlər sürətlə hərəkət edir, işi təkrar etməkdən xoşlanmır, hətta o qədər də keyfiyyətli olmasa belə. Kişi-Buğa isə daha ciddi yanaşır: yavaş-yavaş işləyir, hər bir detalı diqqətlə incələyir. Çox güman ki, kişi-Buğa qadın-Əkizlərin işi bitirməsində kömək edəcək, o isə yeni əlaqələr və ümumi ilham mənbələri axtarışında olacaq.",
          "taurus_cancer_message":
              "83% uyğunluq. Qadın-Buğa və Kişi-Xərçəng mütləq uzunmüddətli və möhkəm münasibət qurmağa qadirdirlər, çünki onların arasında çoxlu ortaq cəhətlər var.",
          "taurus_cancer_love":
              "Qadın-Buğa və Kişi-Xərçəng\nHər ikisi ətraflarında sakit insanlar və münasibətlər istəyirlər. Qadın-Buğa və Kişi-Xərçəng bir-birinə fenomenal şəkildə uyğun gəlir: onlar bir-birlərində axtardıqlarını tapırlar. O, qayğıkeş və sadiq bir qadın tapır, o qadın da kişinin hisslərinə və dəyişkən əhval-ruhiyyəsinə hörmətlə yanaşır (amma çox deyil — məhz lazım olan qədər). Qadın isə öz yanında sakit və incə bir kişi görür, o kişi bütün işlərində onun yanında olan bir yoldaş ola bilər. Onların məhəbbəti — sakit və stabil olacaq, nadir hallarda mübahisə və münaqişələr yaşansa belə. Bu münaqişələr, əsasən, Kişi-Xərçəngin qadının tez bir zamanda onun kaprizlərinə reaksiya verməsini istəməsi səbəbindən yaranır (onun kapriz saymadığı şeylər), lakin qadın hər vəziyyəti uzun-uzadı və diqqətlə dəyərləndirməyə öyrəşib — çox vaxt isə vəziyyət qadın hələ onu araşdırarkən öz-özünə həll olunur.\n\nQadın-Xərçəng və Kişi-Buğa\nQadın-Xərçəng və Kişi-Buğa arasındakı məhəbbət təbii və ahəngdar olur. Hər ikisi sakit həyat tərzinə üstünlük verirlər, evdə qalmağı və sentimental anları paylaşmağı sevirlər. Qadın-Xərçəng Kişi-Buğada hər zaman arzuladığı güclü dəstəyi tapacaq, kişi isə onun zərifliyində, mehribanlığında və qayğısında itəcək. Problemlər bunlar ola bilər: Qadın-Xərçəng Kişi-Buğanın qərarlılığı və cəsarətinin çatışmazlığını hiss edə bilər (o, mübahisələrdən uzaq durmağa üstünlük verir və heç nəyi sübut etməyə ehtiyac duymaz), Kişi-Buğa isə onun əhval-ruhiyyə dəyişiklikləri ilə başa çıxmaqda çətinlik çəkə bilər («aylıq» bir qadın üçün bu normaldır!). Ancaq onlar bir-birlərini həqiqətən sevir və münasibətlərini dəyərləndirirlərsə, hər bir çətinliyin öhdəsindən gələcəklər. Üstəlik, onların birlikdə olmağının müsbət tərəfləri mənfilərindən çoxdur.",
          "taurus_cancer_family":
              "Qadın-Buğa və Kişi-Xərçəng\nOnların ailəsi ideal olacaq. Həm Qadın-Buğa, həm də Kişi-Xərçəng sakit bir ailə həyatına can atırlar və evləndikdə nəyə getdiklərini bilirlər. Onlar əmin olacaqlar ki, onların rahat yuvası həmişə isti və münasibətləri kimi möhkəm qalacaq. Ailədə atmosferi Kişi-Xərçəng təmin edəcək, Qadın-Buğa isə bütün ailə üzvlərinə real və fiziki qayğı göstərəcək. Qadın-Buğa və Kişi-Xərçəngin ailəsində doğulan uşaqlar sevgi və rifah şəraitində böyüyəcəklər. Kişi-Xərçəng, yeri gəlmişkən, hər şeyə icazə verən ata olacaq — ana Buğanın əksinə olaraq.\n\nQadın-Xərçəng və Kişi-Buğa\nOnlar mükəmməl ər-arvad olacaqlar. Qadın-Xərçəng ideal həyat yoldaşıdır: o, mehriban, zərif və lazımi dərəcədə ev işlərini görəndir. Kişi-Buğa isə əsl təminatçı, yaxşı və müdrik ərdir. Onların ailəsi ənənəvi olacaq, ehtimal ki, həyat yoldaşı uşaqlara və ev işlərinə baxacaq, ər isə pul qazanacaq və maddi tərəfi təmin edəcək. Üstəlik, bu ailədə mütləq uşaqlar olacaq: Qadın-Xərçəng uşaqlıqdan övlad arzusundadır, Kişi-Buğa isə xüsusilə ən kiçikləri qorumağı sevir. Yəqin ki, onlar şəhərdən kənarda ev alacaqlar və hər kəsdən bir az uzaqda yaşayacaqlar, öz ailə rahatlıqlarını kənar gözlərdən və lazımsız duyğulardan qoruyacaqlar.",
          "taurus_cancer_friendship":
              "Qadın-Buğa və Kişi-Xərçəng\nQadın-Buğa və Kişi-Xərçəng arasında dostluq uzun və zərif ola bilər. Torpaq və Su elementi nümayəndələri olaraq onlar dostluğa dəyər verir, onu qoruyur və kiçik mübahisələrə görə bitirmirlər. Əlbəttə ki, atmosferə görə məsuliyyət daşıyacaq olan Kişi-Xərçəngdir (o, Qadın-Buğanın əhval-ruhiyyəsini incə hiss edir, çünki qadın özünü nə sevindirdiyini və ya kədərləndirdiyini hər zaman tam dəqiqliklə anlaya bilmir). Onlar hisslərini və fikirlərini bölüşəcəklər, Qadın-Buğa Kişi-Xərçəngin emosional və dolğun həyatında azıdığı zaman ona yaxşı bir praktik məsləhət verəcək. O isə onu sakit sözlərlə dəstəkləyəcək, hər şeyin çökdüyü kimi göründüyü anlarda ona dəstək olacaq.\n\nQadın-Xərçəng və Kişi-Buğa\nQadın-Xərçəng və Kişi-Buğa arasında dostluq çox zərif olacaq. Onlar bir-birlərinə sözsüz dəstək verə biləcəklər, lazım olduqda bir-birinə kömək edəcəklər. Qadın-Xərçəng ona emosional güc və özünəinam verəcək, həyatının bir çıxılmaz vəziyyətdə olduğunu düşündüyü zaman ona güvən verəcək. O isə qadını fiziki olaraq qayğı göstərəcək, stresdən və ya sadəcə, Xərçənglərin hamısına xas olan adi hüznündən yeməyi unutduğu zaman onun qayğısına qalacaq. Onların musiqi və filmlər zövqləri də çox oxşar olacaq: hər ikisi köhnə, gözəl və əbədi olan şeyləri sevir. Bir sözlə, onlar həqiqi dostlar kimi vaxt keçirməkdən məmnun olacaqlar.",
          "taurus_cancer_business":
              "Qadın-Buğa və Kişi-Xərçəng\nOnlar əlbəttə ki, bir yerdə işləyə bilərlər və iş birliyində əsas rol qadın-Buğaya aid olacaq. O, Kişi-Xərçəngin malik olmadığı praqmatizmə malikdir. Kişi-Xərçəng isə, öz növbəsində, həyata keçirəcəkləri ideyanı yarada biləcək. Qadın-Buğa bu ideyanın həyata keçirilmə planını hazırlayacaq, nəticədə onların tandemi müvəffəqiyyətli olacaq. Problemlər Kişi-Xərçəng tənbəlləşib, darıxdırıcı hesab etdiyi işdən qaçmağa başlayanda və Qadın-Buğa onun dahiyanə hesab etdiyi ideyaları tənqid edəndə yaranacaq.\n\nQadın-Xərçəng və Kişi-Buğa\nOnlar çox məhsuldar şəkildə birlikdə işləyə bilərlər, çünki hər ikisi işin mahiyyətini anlamaqda və nəticəyə doğru kiçik addımlarla irəliləməkdə bacarıqlıdır. Ola bilər ki, onların ideyaları çatışmaz olsun — onlar kənardan məsləhət və fikirlərdən istifadə edə bilərlər, lakin bu ideyaları həyata keçirməkdə mükəmməl olacaqlar. Qadın-Xərçəng hər hansı bir layihənin atmosferi və emosional tərəfi ilə məşğul olacaq, Kişi-Buğa isə plan hazırlayacaq və işin detalları ilə məşğul olacaq. Hər halda, bu yaxşı bir komandadır və ehtimal ki, onlar nə işə başlasalar, onu uğurla yerinə yetirəcəklər.",
          "taurus_leo_message":
              "Uyğunluq faizi 88%-dir. Onların münasibətləri torpaq sakitliyi ilə od ehtirasının birliyidir. Amma bir dəqiqə gözləyin — birlikdən danışmaq hələ tezdir.",
          "taurus_leo_love":
              "Qadın-Buğa və Kişi-Şir\nQadın-Buğa və kişi-Şir bir-birini yaxşı başa düşürlər. Kişi-Şir qadın-Buğanın həyatına çatışmayan odu gətirir, qadın-Buğa isə onunla yerə bağlılıq və praktiklik bölüşür. Bəzən qadın-Buğa onun məsələləri emosional həll etməyə meyilli olmasından narahat ola bilər: qadın-Buğa yüksək tonları, həddən artıq ifadəliliyi və münasibətləri aydınlaşdırmağı sevmir. Kişi-Şir isə əksinə, vəziyyət (onun fikrincə) son həddə çatanda sakit və laqeyd qalmağı necə bacardığını anlamır. Onların barışmaları ehtiraslı olacaq (qadın-Buğa bu vəziyyətdə xüsusi bir zövq tapmağı öyrənəcək). Əgər fırtına və sakitlik arasında tarazlıq yaratmağı bacarsalar, uzun müddət münasibətlərini qoruyub saxlaya bilərlər.\n\nQadın-Şir və Kişi-Buğa\nQadın-Şir və kişi-Buğa arasındakı münasibətlər adətən o qədər də hamar getmir və bunun səbəbi belədir. Kişi-Buğa qadını öz emosional təmkinliliyi və zahiri sakitliyi, möhkəmliyi ilə cəlb edir. Qadın-Şir ona olduqca cazibədar görünür: qadın-Şir xüsusilə onu maraqlandıran birinə təəssürat yaratmağı bacarır. Amma bir şey onu narahat edir: onun duyğusal keçilməzliyi. Görünür ki, o, onun ruhuna və düşüncələrinə nə qədər nüfuz etməyə çalışsa da, kişi-Buğa bir o qədər müqavimət göstərir və onlar arasında daha yüksək bir divar tikir (məcazi mənada, əlbəttə). Əgər aralarında romantik münasibətlər yaranarsa, hər iki tərəf bir-birinə tam qovuşma və rahatlıq hiss etməzlər. Qadın-Şir daim özünü nəzarətdə saxlamalı olur ki, təsadüfən bu əlçatmaz kişini incitməsin, kişi-Buğa isə zaman-zaman narahat olur: bəlkə də onu özünə çox yaxın buraxıb və bu, ona emosional travmalar gətirəcək.",
          "taurus_leo_family":
              "Qadın-Buğa və Kişi-Şir\nNikahda qadın-Buğa və kişi-Şir axtardıqlarını tapacaqlar: qadın sabitlik və möhkəm dayaq, kişi isə sevgi və ürəklik tapacaq. Əlbəttə, aralarında bəzən mübahisələr və münaqişələr baş verəcək: kişi-Şirin asanlıqla alışan təbiəti heç yerə getmir, amma onlar uzun illər ailələrini qorumağa qadirdirlər. Onların ailəsində uşaqlar lazım olan hər şeyi alacaqlar: analarından yemək və təmiz paltar (eləcə də qeyri-adi nəvaziş) və atalarından isə daxili potensiallarına diqqət yetirəcəklər. Kişi-Şir uşaqlarının istedadlarına çox həssas yanaşır: onları kəşf edir və böyük zövqlə inkişaf etdirir.\n\nQadın-Şir və Kişi-Buğa\nƏgər onlar evlənsələr, nikahlarını qoruyub saxlamaq o qədər də asan olmayacaq. Qadın-Şir mükəmməl evdar qadın ola bilər, kişi-Buğa isə evdə rahatlıq və rahatlığı çox yüksək qiymətləndirir. O, həmçinin yaxşı ər olacaq: çalışqan və qayğıkeş, amma ondan parlaq duyğular və hisslərin təzahürünü gözləmək olmaz. Ailə rollarının bölgüsü baxımından bu birlik mükəmməldir, lakin ər-arvadın bir-biri ilə anlaşması çətin olacaq. Həmin o uyğun gəlməyən temperamentlər öz təsirini göstərəcək: qadın-Şirə ünsiyyət qurmaq istəyərkən, kişi-Buğa isə öz arvadından istirahət etmək istəyəcək.",
          "taurus_leo_friendship":
              "Qadın-Buğa və Kişi-Şir\nQadın-Buğa və kişi-Şir arasında yaxşı dostluq yarana bilər. Qadın-Buğa öz dostunun nə qədər açıq və səmimi olduğunu hiss edəcək, kişi-Şir isə hər zaman öz rəfiqəsinə güvənə biləcəyini anlayacaq. Bəlkə də, aralarında uzun sentimentallı söhbətlər olmayacaq, amma möhkəm, sakit və sabit bir şey olacaq. Yeri gəlmişkən, bu ikisinin birgə hobbiləri ola bilər, məsələn, teatr və ya vokal sənəti: kişi-Şir özünü artistik olaraq ifadə etməyi çox sevir, qadın-Buğa isə istənilən obrazı canlandıra bilər.\n\nQadın-Şir və Kişi-Buğa\nQadın-Şir və kişi-Buğa arasında dostluq çox möhkəm ola bilər, əgər qadın-Şir kişi-Buğanın müəyyən etdiyi sərhədləri aşmasa. Qeyd olunduğu kimi, kişi-Buğa öz ruhuna həddindən artıq israrla müdaxilə edilməsinə dözmür və deməli, dostluq yaxınlığının tempini də məhz o tənzimləyəcək. Əgər bu, qadın-Şir üçün inciklik səbəbi olmayacaqsa, bir müddət sonra onlar öz ünsiyyətlərində qızıl ortanı tapa biləcəklər, amma yenə də müəyyən bir rahatlıq çatışmazlığı hiss olunacaq.",
          "taurus_leo_business":
              "Qadın-Buğa və Kişi-Şir\nBirlikdə işləyərkən qadın-Buğa və kişi-Şir demək olar ki, istənilən ideyanı həyata keçirmək bacarığına malikdirlər. Kişi-Şir lazımi təzyiqə malikdir, qadın-Buğanı “yandırmağı” və onu işin vacib hissəsini yerinə yetirməyə sövq etməyi bacarır. Qadın-Buğa tərəfdaş kimi kişiyə-Şirin qərarları emosional həll etməyə meyilli olması xoşuna gəlməyəcək (axı o, hər zaman məntiqə sadiq qalmağın tərəfdarıdır). Kişi-Şiri narahat edən isə qadın-Buğanın daim nəzarət etmək arzusu olacaq — o cümlədən onun tərəfindən yerinə yetirilməyən işlərə də. Əgər onlar əməkdaşlıqlarının üstünlüklərinə diqqət yetirib mənfi cəhətlərini bir kənara qoyarlarsa, onları əsl uğur gözləyir.\n\nQadın-Şir və Kişi-Buğa\nBirlikdə işləyərkən bu ikisi əla nəticələr əldə edə bilərlər. Kişi-Buğa diqqətli yanaşma və təfərrüatlı yanaşma tələb edən hər şeydə yaxşıdır, qadın-Şir isə insanlarla emosional əlaqələr qurmaq və resursları idarə etmək vəzifələri ilə əla bacarır. İkisi birlikdə hər hansı bir şey istehsal edən kiçik bir şirkəti tam qaydasında saxlaya bilərlər — onların 'qızıl' keyfiyyətlərinin tətbiq sahəsi son dərəcə genişdir."
        },
        'ru_RU': {
          'welcome': 'Добро пожаловать',
          'appName': "N9 DESTINY HUB",
          'appSlogan':
              "Ваш путь к счастью, любви и изобилию начинается здесь: получите свой персональный гороскоп, медитацию и многое другое!",
          'start': 'Начать',
          'know': "Давай узнаем друг друга",
          'nameQuestion': 'Как я могу тебя звать?',
          'name': 'Имя',
          'birthQuestion': 'Когда ты родился?',
          'birthOfDate': 'Birth of date',
          'timeQuestion':
              'Мне нужно время твоего рождения, чтобы дать точные прогнозы. Если ты не знаешь, просто отметь как 12:00',
          'time': 'Время рождения',
          'cityQuestion':
              'Наконец последний вопрос! Напишите ваш город рождения',
          'city': 'Город',
          'wrongEmail': 'Email не верный',
          'noInfo': 'Это поле не может быть пустым',
          'description': 'Описание',
          'love': 'Любовь',
          'character': 'Характер',
          'career': 'Карьера',
          'health': 'Здоровье',
          'hello': 'Привет',
          "next": "Cледующий",
          'birthdate_register':
              "Чтобы предоставить вам персональный гороскоп, нам нужно знать вашу дату рождения, которая также важна для определения вашего знака зодиака.",
          "check_love": "Узнай свою любовную совместимость!",
          "explore_with_tests":
              "Проверьте свою совместимость в любви с помощью наших проницательных тестов"
        }
      };
}
